<?xml version="1.0" ?>
<!DOCTYPE main [
  <!ELEMENT main (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (TITLU_RAPORT?,ANEXA?,COD_ORDONATOR?,DEN_ORDONATOR?,CODFISCAL?,COD_PROGRAM_OPERATIONAL?,DEN_PROGRAM_OPERATIONAL?,DEN_SURSA?,ORDINE_AFISARE?,COD_INDICATOR?,DEN_INDICATOR?,CATEGORIE_RAND?,REALIZARI_PANA_IN_2022?,REALIZARI_2023?,EXECUTIE_PRELIMINATA_2024?,PROGRAM_2025?,ESTIMARI_2026?,ESTIMARI_2027?,ESTIMARI_2028?,ANII_URMATORI?,TOTAL?)+>
  <!ELEMENT TITLU_RAPORT (#PCDATA)>
  <!ELEMENT ANEXA (#PCDATA)>
  <!ELEMENT COD_ORDONATOR (#PCDATA)>
  <!ELEMENT DEN_ORDONATOR (#PCDATA)>
  <!ELEMENT CODFISCAL (#PCDATA)>
  <!ELEMENT COD_PROGRAM_OPERATIONAL (#PCDATA)>
  <!ELEMENT DEN_PROGRAM_OPERATIONAL (#PCDATA)>
  <!ELEMENT DEN_SURSA (#PCDATA)>
  <!ELEMENT ORDINE_AFISARE (#PCDATA)>
  <!ELEMENT COD_INDICATOR (#PCDATA)>
  <!ELEMENT DEN_INDICATOR (#PCDATA)>
  <!ELEMENT CATEGORIE_RAND (#PCDATA)>
  <!ELEMENT REALIZARI_PANA_IN_2022 (#PCDATA)>
  <!ELEMENT REALIZARI_2023 (#PCDATA)>
  <!ELEMENT EXECUTIE_PRELIMINATA_2024 (#PCDATA)>
  <!ELEMENT PROGRAM_2025 (#PCDATA)>
  <!ELEMENT ESTIMARI_2026 (#PCDATA)>
  <!ELEMENT ESTIMARI_2027 (#PCDATA)>
  <!ELEMENT ESTIMARI_2028 (#PCDATA)>
  <!ELEMENT ANII_URMATORI (#PCDATA)>
  <!ELEMENT TOTAL (#PCDATA)>
]>
<main>
  <DATA_RECORD>
    <TITLU_RAPORT>CHELTUIELI DIN BUGETUL DE STAT NECESARE SUSTINERII DERULARII PROIECTELOR FINANTATE DIN FEN POSTADERARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E., POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI ALTOR FACILITATI SI INSTRUMENTE POSTADERARE PRECUM SI REFORMELOR/INVESTITIILOR AFERENTE PNRR</TITLU_RAPORT>
    <ANEXA>Anexa nr.24</ANEXA>
    <COD_ORDONATOR>13</COD_ORDONATOR>
    <DEN_ORDONATOR>Secretariatul General al Guvernului</DEN_ORDONATOR>
    <CODFISCAL>4283422</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>113</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Planul National de Redresare si Rezilienta</DEN_PROGRAM_OPERATIONAL>
    <DEN_SURSA>Total surse</DEN_SURSA>
    <ORDINE_AFISARE>1</ORDINE_AFISARE>
    <COD_INDICATOR>5000</COD_INDICATOR>
    <DEN_INDICATOR>TOTAL GENERAL</DEN_INDICATOR>
    <CATEGORIE_RAND>I.Credite de angajamente</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>16756</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>0</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>16756</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>CHELTUIELI DIN BUGETUL DE STAT NECESARE SUSTINERII DERULARII PROIECTELOR FINANTATE DIN FEN POSTADERARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E., POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI ALTOR FACILITATI SI INSTRUMENTE POSTADERARE PRECUM SI REFORMELOR/INVESTITIILOR AFERENTE PNRR</TITLU_RAPORT>
    <ANEXA>Anexa nr.24</ANEXA>
    <COD_ORDONATOR>13</COD_ORDONATOR>
    <DEN_ORDONATOR>Secretariatul General al Guvernului</DEN_ORDONATOR>
    <CODFISCAL>4283422</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>113</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Planul National de Redresare si Rezilienta</DEN_PROGRAM_OPERATIONAL>
    <DEN_SURSA>Total surse</DEN_SURSA>
    <ORDINE_AFISARE>1</ORDINE_AFISARE>
    <COD_INDICATOR>5000</COD_INDICATOR>
    <DEN_INDICATOR>TOTAL GENERAL</DEN_INDICATOR>
    <CATEGORIE_RAND>II.Credite bugetare</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>8256</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>4590</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>12846</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>CHELTUIELI DIN BUGETUL DE STAT NECESARE SUSTINERII DERULARII PROIECTELOR FINANTATE DIN FEN POSTADERARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E., POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI ALTOR FACILITATI SI INSTRUMENTE POSTADERARE PRECUM SI REFORMELOR/INVESTITIILOR AFERENTE PNRR</TITLU_RAPORT>
    <ANEXA>Anexa nr.24</ANEXA>
    <COD_ORDONATOR>13</COD_ORDONATOR>
    <DEN_ORDONATOR>Secretariatul General al Guvernului</DEN_ORDONATOR>
    <CODFISCAL>4283422</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>113</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Planul National de Redresare si Rezilienta</DEN_PROGRAM_OPERATIONAL>
    <DEN_SURSA>Buget de stat</DEN_SURSA>
    <ORDINE_AFISARE>2</ORDINE_AFISARE>
    <COD_INDICATOR>5001</COD_INDICATOR>
    <DEN_INDICATOR>CHELTUIELI - BUGET DE STAT</DEN_INDICATOR>
    <CATEGORIE_RAND>I.Credite de angajamente</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>16756</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>0</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>16756</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>CHELTUIELI DIN BUGETUL DE STAT NECESARE SUSTINERII DERULARII PROIECTELOR FINANTATE DIN FEN POSTADERARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E., POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI ALTOR FACILITATI SI INSTRUMENTE POSTADERARE PRECUM SI REFORMELOR/INVESTITIILOR AFERENTE PNRR</TITLU_RAPORT>
    <ANEXA>Anexa nr.24</ANEXA>
    <COD_ORDONATOR>13</COD_ORDONATOR>
    <DEN_ORDONATOR>Secretariatul General al Guvernului</DEN_ORDONATOR>
    <CODFISCAL>4283422</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>113</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Planul National de Redresare si Rezilienta</DEN_PROGRAM_OPERATIONAL>
    <DEN_SURSA>Buget de stat</DEN_SURSA>
    <ORDINE_AFISARE>2</ORDINE_AFISARE>
    <COD_INDICATOR>5001</COD_INDICATOR>
    <DEN_INDICATOR>CHELTUIELI - BUGET DE STAT</DEN_INDICATOR>
    <CATEGORIE_RAND>II.Credite bugetare</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>8256</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>4590</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>12846</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>CHELTUIELI DIN BUGETUL DE STAT NECESARE SUSTINERII DERULARII PROIECTELOR FINANTATE DIN FEN POSTADERARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E., POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI ALTOR FACILITATI SI INSTRUMENTE POSTADERARE PRECUM SI REFORMELOR/INVESTITIILOR AFERENTE PNRR</TITLU_RAPORT>
    <ANEXA>Anexa nr.24</ANEXA>
    <COD_ORDONATOR>13</COD_ORDONATOR>
    <DEN_ORDONATOR>Secretariatul General al Guvernului</DEN_ORDONATOR>
    <CODFISCAL>4283422</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>113</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Planul National de Redresare si Rezilienta</DEN_PROGRAM_OPERATIONAL>
    <DEN_SURSA>Buget de stat</DEN_SURSA>
    <ORDINE_AFISARE>3</ORDINE_AFISARE>
    <COD_INDICATOR>5101</COD_INDICATOR>
    <DEN_INDICATOR>AUTORITATI PUBLICE SI ACTIUNI EXTERNE</DEN_INDICATOR>
    <CATEGORIE_RAND>I.Credite de angajamente</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>16756</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>0</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>16756</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>CHELTUIELI DIN BUGETUL DE STAT NECESARE SUSTINERII DERULARII PROIECTELOR FINANTATE DIN FEN POSTADERARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E., POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI ALTOR FACILITATI SI INSTRUMENTE POSTADERARE PRECUM SI REFORMELOR/INVESTITIILOR AFERENTE PNRR</TITLU_RAPORT>
    <ANEXA>Anexa nr.24</ANEXA>
    <COD_ORDONATOR>13</COD_ORDONATOR>
    <DEN_ORDONATOR>Secretariatul General al Guvernului</DEN_ORDONATOR>
    <CODFISCAL>4283422</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>113</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Planul National de Redresare si Rezilienta</DEN_PROGRAM_OPERATIONAL>
    <DEN_SURSA>Buget de stat</DEN_SURSA>
    <ORDINE_AFISARE>3</ORDINE_AFISARE>
    <COD_INDICATOR>5101</COD_INDICATOR>
    <DEN_INDICATOR>AUTORITATI PUBLICE SI ACTIUNI EXTERNE</DEN_INDICATOR>
    <CATEGORIE_RAND>II.Credite bugetare</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>8256</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>4590</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>12846</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>CHELTUIELI DIN BUGETUL DE STAT NECESARE SUSTINERII DERULARII PROIECTELOR FINANTATE DIN FEN POSTADERARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E., POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI ALTOR FACILITATI SI INSTRUMENTE POSTADERARE PRECUM SI REFORMELOR/INVESTITIILOR AFERENTE PNRR</TITLU_RAPORT>
    <ANEXA>Anexa nr.24</ANEXA>
    <COD_ORDONATOR>13</COD_ORDONATOR>
    <DEN_ORDONATOR>Secretariatul General al Guvernului</DEN_ORDONATOR>
    <CODFISCAL>4283422</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>113</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Planul National de Redresare si Rezilienta</DEN_PROGRAM_OPERATIONAL>
    <DEN_SURSA>Buget de stat</DEN_SURSA>
    <ORDINE_AFISARE>4</ORDINE_AFISARE>
    <COD_INDICATOR>510160</COD_INDICATOR>
    <DEN_INDICATOR>TITLUL XII PROIECTE CU FINANTARE DIN SUMELE REPREZENTAND ASISTENTA FINANCIARA NERAMBURSABILA AFERENTA PNRR</DEN_INDICATOR>
    <CATEGORIE_RAND>I.Credite de angajamente</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>16756</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>0</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>16756</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>CHELTUIELI DIN BUGETUL DE STAT NECESARE SUSTINERII DERULARII PROIECTELOR FINANTATE DIN FEN POSTADERARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E., POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI ALTOR FACILITATI SI INSTRUMENTE POSTADERARE PRECUM SI REFORMELOR/INVESTITIILOR AFERENTE PNRR</TITLU_RAPORT>
    <ANEXA>Anexa nr.24</ANEXA>
    <COD_ORDONATOR>13</COD_ORDONATOR>
    <DEN_ORDONATOR>Secretariatul General al Guvernului</DEN_ORDONATOR>
    <CODFISCAL>4283422</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>113</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Planul National de Redresare si Rezilienta</DEN_PROGRAM_OPERATIONAL>
    <DEN_SURSA>Buget de stat</DEN_SURSA>
    <ORDINE_AFISARE>4</ORDINE_AFISARE>
    <COD_INDICATOR>510160</COD_INDICATOR>
    <DEN_INDICATOR>TITLUL XII PROIECTE CU FINANTARE DIN SUMELE REPREZENTAND ASISTENTA FINANCIARA NERAMBURSABILA AFERENTA PNRR</DEN_INDICATOR>
    <CATEGORIE_RAND>II.Credite bugetare</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>8256</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>4590</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>12846</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>CHELTUIELI DIN BUGETUL DE STAT NECESARE SUSTINERII DERULARII PROIECTELOR FINANTATE DIN FEN POSTADERARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E., POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI ALTOR FACILITATI SI INSTRUMENTE POSTADERARE PRECUM SI REFORMELOR/INVESTITIILOR AFERENTE PNRR</TITLU_RAPORT>
    <ANEXA>Anexa nr.24</ANEXA>
    <COD_ORDONATOR>13</COD_ORDONATOR>
    <DEN_ORDONATOR>Secretariatul General al Guvernului</DEN_ORDONATOR>
    <CODFISCAL>4283422</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>113</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Planul National de Redresare si Rezilienta</DEN_PROGRAM_OPERATIONAL>
    <DEN_SURSA>Buget de stat</DEN_SURSA>
    <ORDINE_AFISARE>5</ORDINE_AFISARE>
    <COD_INDICATOR>51016004</COD_INDICATOR>
    <DEN_INDICATOR>Transferuri din bugetul de stat catre beneficiari institutii publice finantate partial sau integral din venituri proprii pentru derularea proiectelor din PNRR</DEN_INDICATOR>
    <CATEGORIE_RAND>I.Credite de angajamente</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>16756</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>0</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>16756</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>CHELTUIELI DIN BUGETUL DE STAT NECESARE SUSTINERII DERULARII PROIECTELOR FINANTATE DIN FEN POSTADERARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E., POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI ALTOR FACILITATI SI INSTRUMENTE POSTADERARE PRECUM SI REFORMELOR/INVESTITIILOR AFERENTE PNRR</TITLU_RAPORT>
    <ANEXA>Anexa nr.24</ANEXA>
    <COD_ORDONATOR>13</COD_ORDONATOR>
    <DEN_ORDONATOR>Secretariatul General al Guvernului</DEN_ORDONATOR>
    <CODFISCAL>4283422</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>113</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Planul National de Redresare si Rezilienta</DEN_PROGRAM_OPERATIONAL>
    <DEN_SURSA>Buget de stat</DEN_SURSA>
    <ORDINE_AFISARE>5</ORDINE_AFISARE>
    <COD_INDICATOR>51016004</COD_INDICATOR>
    <DEN_INDICATOR>Transferuri din bugetul de stat catre beneficiari institutii publice finantate partial sau integral din venituri proprii pentru derularea proiectelor din PNRR</DEN_INDICATOR>
    <CATEGORIE_RAND>II.Credite bugetare</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>8256</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>4590</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>12846</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>CHELTUIELI DIN BUGETUL DE STAT NECESARE SUSTINERII DERULARII PROIECTELOR FINANTATE DIN FEN POSTADERARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E., POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI ALTOR FACILITATI SI INSTRUMENTE POSTADERARE PRECUM SI REFORMELOR/INVESTITIILOR AFERENTE PNRR</TITLU_RAPORT>
    <ANEXA>Anexa nr.24</ANEXA>
    <COD_ORDONATOR>13</COD_ORDONATOR>
    <DEN_ORDONATOR>Secretariatul General al Guvernului</DEN_ORDONATOR>
    <CODFISCAL>4283422</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>113</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Planul National de Redresare si Rezilienta</DEN_PROGRAM_OPERATIONAL>
    <DEN_SURSA>Buget de stat</DEN_SURSA>
    <ORDINE_AFISARE>6</ORDINE_AFISARE>
    <COD_INDICATOR>5101600401</COD_INDICATOR>
    <DEN_INDICATOR> Fonduri europene nerambursabile</DEN_INDICATOR>
    <CATEGORIE_RAND>II.Credite bugetare</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>2818</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>3857</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>6675</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>CHELTUIELI DIN BUGETUL DE STAT NECESARE SUSTINERII DERULARII PROIECTELOR FINANTATE DIN FEN POSTADERARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E., POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI ALTOR FACILITATI SI INSTRUMENTE POSTADERARE PRECUM SI REFORMELOR/INVESTITIILOR AFERENTE PNRR</TITLU_RAPORT>
    <ANEXA>Anexa nr.24</ANEXA>
    <COD_ORDONATOR>13</COD_ORDONATOR>
    <DEN_ORDONATOR>Secretariatul General al Guvernului</DEN_ORDONATOR>
    <CODFISCAL>4283422</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>113</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Planul National de Redresare si Rezilienta</DEN_PROGRAM_OPERATIONAL>
    <DEN_SURSA>Buget de stat</DEN_SURSA>
    <ORDINE_AFISARE>7</ORDINE_AFISARE>
    <COD_INDICATOR>5101600402</COD_INDICATOR>
    <DEN_INDICATOR> Finantare publica nationala</DEN_INDICATOR>
    <CATEGORIE_RAND>I.Credite de angajamente</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>16756</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>0</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>16756</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>CHELTUIELI DIN BUGETUL DE STAT NECESARE SUSTINERII DERULARII PROIECTELOR FINANTATE DIN FEN POSTADERARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E., POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI ALTOR FACILITATI SI INSTRUMENTE POSTADERARE PRECUM SI REFORMELOR/INVESTITIILOR AFERENTE PNRR</TITLU_RAPORT>
    <ANEXA>Anexa nr.24</ANEXA>
    <COD_ORDONATOR>13</COD_ORDONATOR>
    <DEN_ORDONATOR>Secretariatul General al Guvernului</DEN_ORDONATOR>
    <CODFISCAL>4283422</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>113</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Planul National de Redresare si Rezilienta</DEN_PROGRAM_OPERATIONAL>
    <DEN_SURSA>Buget de stat</DEN_SURSA>
    <ORDINE_AFISARE>7</ORDINE_AFISARE>
    <COD_INDICATOR>5101600402</COD_INDICATOR>
    <DEN_INDICATOR> Finantare publica nationala</DEN_INDICATOR>
    <CATEGORIE_RAND>II.Credite bugetare</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>4902</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>0</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>4902</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>CHELTUIELI DIN BUGETUL DE STAT NECESARE SUSTINERII DERULARII PROIECTELOR FINANTATE DIN FEN POSTADERARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E., POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI ALTOR FACILITATI SI INSTRUMENTE POSTADERARE PRECUM SI REFORMELOR/INVESTITIILOR AFERENTE PNRR</TITLU_RAPORT>
    <ANEXA>Anexa nr.24</ANEXA>
    <COD_ORDONATOR>13</COD_ORDONATOR>
    <DEN_ORDONATOR>Secretariatul General al Guvernului</DEN_ORDONATOR>
    <CODFISCAL>4283422</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>113</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Planul National de Redresare si Rezilienta</DEN_PROGRAM_OPERATIONAL>
    <DEN_SURSA>Buget de stat</DEN_SURSA>
    <ORDINE_AFISARE>8</ORDINE_AFISARE>
    <COD_INDICATOR>5101600403</COD_INDICATOR>
    <DEN_INDICATOR> Sume aferente TVA</DEN_INDICATOR>
    <CATEGORIE_RAND>II.Credite bugetare</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>536</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>733</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>1269</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>CHELTUIELI DIN BUGETUL DE STAT NECESARE SUSTINERII DERULARII PROIECTELOR FINANTATE DIN FEN POSTADERARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E., POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI ALTOR FACILITATI SI INSTRUMENTE POSTADERARE PRECUM SI REFORMELOR/INVESTITIILOR AFERENTE PNRR</TITLU_RAPORT>
    <ANEXA>Anexa nr.24</ANEXA>
    <COD_ORDONATOR>13</COD_ORDONATOR>
    <DEN_ORDONATOR>Secretariatul General al Guvernului</DEN_ORDONATOR>
    <CODFISCAL>4283422</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>233</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Reforma 8: Reformarea sistemului national de achizitii publice</DEN_PROGRAM_OPERATIONAL>
    <DEN_SURSA>Total surse</DEN_SURSA>
    <ORDINE_AFISARE>9</ORDINE_AFISARE>
    <COD_INDICATOR>5000</COD_INDICATOR>
    <DEN_INDICATOR>TOTAL GENERAL</DEN_INDICATOR>
    <CATEGORIE_RAND>I.Credite de angajamente</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>11841</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>0</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>11841</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>CHELTUIELI DIN BUGETUL DE STAT NECESARE SUSTINERII DERULARII PROIECTELOR FINANTATE DIN FEN POSTADERARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E., POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI ALTOR FACILITATI SI INSTRUMENTE POSTADERARE PRECUM SI REFORMELOR/INVESTITIILOR AFERENTE PNRR</TITLU_RAPORT>
    <ANEXA>Anexa nr.24</ANEXA>
    <COD_ORDONATOR>13</COD_ORDONATOR>
    <DEN_ORDONATOR>Secretariatul General al Guvernului</DEN_ORDONATOR>
    <CODFISCAL>4283422</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>233</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Reforma 8: Reformarea sistemului national de achizitii publice</DEN_PROGRAM_OPERATIONAL>
    <DEN_SURSA>Total surse</DEN_SURSA>
    <ORDINE_AFISARE>9</ORDINE_AFISARE>
    <COD_INDICATOR>5000</COD_INDICATOR>
    <DEN_INDICATOR>TOTAL GENERAL</DEN_INDICATOR>
    <CATEGORIE_RAND>II.Credite bugetare</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>1926</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>3956</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>5959</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>11841</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>CHELTUIELI DIN BUGETUL DE STAT NECESARE SUSTINERII DERULARII PROIECTELOR FINANTATE DIN FEN POSTADERARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E., POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI ALTOR FACILITATI SI INSTRUMENTE POSTADERARE PRECUM SI REFORMELOR/INVESTITIILOR AFERENTE PNRR</TITLU_RAPORT>
    <ANEXA>Anexa nr.24</ANEXA>
    <COD_ORDONATOR>13</COD_ORDONATOR>
    <DEN_ORDONATOR>Secretariatul General al Guvernului</DEN_ORDONATOR>
    <CODFISCAL>4283422</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>233</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Reforma 8: Reformarea sistemului national de achizitii publice</DEN_PROGRAM_OPERATIONAL>
    <DEN_SURSA>Buget de stat</DEN_SURSA>
    <ORDINE_AFISARE>10</ORDINE_AFISARE>
    <COD_INDICATOR>5001</COD_INDICATOR>
    <DEN_INDICATOR>CHELTUIELI - BUGET DE STAT</DEN_INDICATOR>
    <CATEGORIE_RAND>I.Credite de angajamente</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>11841</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>0</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>11841</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>CHELTUIELI DIN BUGETUL DE STAT NECESARE SUSTINERII DERULARII PROIECTELOR FINANTATE DIN FEN POSTADERARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E., POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI ALTOR FACILITATI SI INSTRUMENTE POSTADERARE PRECUM SI REFORMELOR/INVESTITIILOR AFERENTE PNRR</TITLU_RAPORT>
    <ANEXA>Anexa nr.24</ANEXA>
    <COD_ORDONATOR>13</COD_ORDONATOR>
    <DEN_ORDONATOR>Secretariatul General al Guvernului</DEN_ORDONATOR>
    <CODFISCAL>4283422</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>233</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Reforma 8: Reformarea sistemului national de achizitii publice</DEN_PROGRAM_OPERATIONAL>
    <DEN_SURSA>Buget de stat</DEN_SURSA>
    <ORDINE_AFISARE>10</ORDINE_AFISARE>
    <COD_INDICATOR>5001</COD_INDICATOR>
    <DEN_INDICATOR>CHELTUIELI - BUGET DE STAT</DEN_INDICATOR>
    <CATEGORIE_RAND>II.Credite bugetare</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>1926</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>3956</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>5959</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>11841</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>CHELTUIELI DIN BUGETUL DE STAT NECESARE SUSTINERII DERULARII PROIECTELOR FINANTATE DIN FEN POSTADERARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E., POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI ALTOR FACILITATI SI INSTRUMENTE POSTADERARE PRECUM SI REFORMELOR/INVESTITIILOR AFERENTE PNRR</TITLU_RAPORT>
    <ANEXA>Anexa nr.24</ANEXA>
    <COD_ORDONATOR>13</COD_ORDONATOR>
    <DEN_ORDONATOR>Secretariatul General al Guvernului</DEN_ORDONATOR>
    <CODFISCAL>4283422</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>233</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Reforma 8: Reformarea sistemului national de achizitii publice</DEN_PROGRAM_OPERATIONAL>
    <DEN_SURSA>Buget de stat</DEN_SURSA>
    <ORDINE_AFISARE>11</ORDINE_AFISARE>
    <COD_INDICATOR>5101</COD_INDICATOR>
    <DEN_INDICATOR>AUTORITATI PUBLICE SI ACTIUNI EXTERNE</DEN_INDICATOR>
    <CATEGORIE_RAND>I.Credite de angajamente</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>11841</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>0</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>11841</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>CHELTUIELI DIN BUGETUL DE STAT NECESARE SUSTINERII DERULARII PROIECTELOR FINANTATE DIN FEN POSTADERARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E., POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI ALTOR FACILITATI SI INSTRUMENTE POSTADERARE PRECUM SI REFORMELOR/INVESTITIILOR AFERENTE PNRR</TITLU_RAPORT>
    <ANEXA>Anexa nr.24</ANEXA>
    <COD_ORDONATOR>13</COD_ORDONATOR>
    <DEN_ORDONATOR>Secretariatul General al Guvernului</DEN_ORDONATOR>
    <CODFISCAL>4283422</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>233</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Reforma 8: Reformarea sistemului national de achizitii publice</DEN_PROGRAM_OPERATIONAL>
    <DEN_SURSA>Buget de stat</DEN_SURSA>
    <ORDINE_AFISARE>11</ORDINE_AFISARE>
    <COD_INDICATOR>5101</COD_INDICATOR>
    <DEN_INDICATOR>AUTORITATI PUBLICE SI ACTIUNI EXTERNE</DEN_INDICATOR>
    <CATEGORIE_RAND>II.Credite bugetare</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>1926</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>3956</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>5959</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>11841</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>CHELTUIELI DIN BUGETUL DE STAT NECESARE SUSTINERII DERULARII PROIECTELOR FINANTATE DIN FEN POSTADERARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E., POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI ALTOR FACILITATI SI INSTRUMENTE POSTADERARE PRECUM SI REFORMELOR/INVESTITIILOR AFERENTE PNRR</TITLU_RAPORT>
    <ANEXA>Anexa nr.24</ANEXA>
    <COD_ORDONATOR>13</COD_ORDONATOR>
    <DEN_ORDONATOR>Secretariatul General al Guvernului</DEN_ORDONATOR>
    <CODFISCAL>4283422</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>233</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Reforma 8: Reformarea sistemului national de achizitii publice</DEN_PROGRAM_OPERATIONAL>
    <DEN_SURSA>Buget de stat</DEN_SURSA>
    <ORDINE_AFISARE>12</ORDINE_AFISARE>
    <COD_INDICATOR>510160</COD_INDICATOR>
    <DEN_INDICATOR>TITLUL XII PROIECTE CU FINANTARE DIN SUMELE REPREZENTAND ASISTENTA FINANCIARA NERAMBURSABILA AFERENTA PNRR</DEN_INDICATOR>
    <CATEGORIE_RAND>I.Credite de angajamente</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>11841</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>0</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>11841</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>CHELTUIELI DIN BUGETUL DE STAT NECESARE SUSTINERII DERULARII PROIECTELOR FINANTATE DIN FEN POSTADERARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E., POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI ALTOR FACILITATI SI INSTRUMENTE POSTADERARE PRECUM SI REFORMELOR/INVESTITIILOR AFERENTE PNRR</TITLU_RAPORT>
    <ANEXA>Anexa nr.24</ANEXA>
    <COD_ORDONATOR>13</COD_ORDONATOR>
    <DEN_ORDONATOR>Secretariatul General al Guvernului</DEN_ORDONATOR>
    <CODFISCAL>4283422</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>233</COD_PROGRAM_OPERATIONAL>