<?xml version="1.0" ?>
<!DOCTYPE main [
  <!ELEMENT main (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (TITLU_RAPORT?,ANEXA?,COD_ORDONATOR?,DEN_ORDONATOR?,CODFISCAL?,COD_PROGRAM_OPERATIONAL?,DEN_PROGRAM_OPERATIONAL?,COD_PROIECT?,DEN_PROIECT?,COD_FOND_FINANTARE?,DEN_FOND_FINANTARE?,DEN_SURSA?,COD_INDICATOR?,DEN_INDICATOR?,CATEGORIE_RAND?,REALIZARI_PANA_IN_2022?,REALIZARI_2023?,EXECUTIE_PRELIMINATA_2024?,PROGRAM_2025?,ESTIMARI_2026?,ESTIMARI_2027?,ESTIMARI_2028?,ANII_URMATORI?,TOTAL?)+>
  <!ELEMENT TITLU_RAPORT (#PCDATA)>
  <!ELEMENT ANEXA (#PCDATA)>
  <!ELEMENT COD_ORDONATOR (#PCDATA)>
  <!ELEMENT DEN_ORDONATOR (#PCDATA)>
  <!ELEMENT CODFISCAL (#PCDATA)>
  <!ELEMENT COD_PROGRAM_OPERATIONAL (#PCDATA)>
  <!ELEMENT DEN_PROGRAM_OPERATIONAL (#PCDATA)>
  <!ELEMENT COD_PROIECT (#PCDATA)>
  <!ELEMENT DEN_PROIECT (#PCDATA)>
  <!ELEMENT COD_FOND_FINANTARE (#PCDATA)>
  <!ELEMENT DEN_FOND_FINANTARE (#PCDATA)>
  <!ELEMENT DEN_SURSA (#PCDATA)>
  <!ELEMENT COD_INDICATOR (#PCDATA)>
  <!ELEMENT DEN_INDICATOR (#PCDATA)>
  <!ELEMENT CATEGORIE_RAND (#PCDATA)>
  <!ELEMENT REALIZARI_PANA_IN_2022 (#PCDATA)>
  <!ELEMENT REALIZARI_2023 (#PCDATA)>
  <!ELEMENT EXECUTIE_PRELIMINATA_2024 (#PCDATA)>
  <!ELEMENT PROGRAM_2025 (#PCDATA)>
  <!ELEMENT ESTIMARI_2026 (#PCDATA)>
  <!ELEMENT ESTIMARI_2027 (#PCDATA)>
  <!ELEMENT ESTIMARI_2028 (#PCDATA)>
  <!ELEMENT ANII_URMATORI (#PCDATA)>
  <!ELEMENT TOTAL (#PCDATA)>
]>
<main>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROIECTULUI FINANTAT/PROPUS LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 3/04/01</ANEXA>
    <COD_ORDONATOR>21</COD_ORDONATOR>
    <DEN_ORDONATOR>Ministerul Muncii, Familiei, Tineretului si Solidaritatii Sociale</DEN_ORDONATOR>
    <CODFISCAL>11370190</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>110</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Programul operational Educatie si ocupare 2021-2027</DEN_PROGRAM_OPERATIONAL>
    <COD_PROIECT>23830</COD_PROIECT>
    <DEN_PROIECT>SMART SPO - Servicii moderne, accesibile si pregatite pentru viitor</DEN_PROIECT>
    <COD_FOND_FINANTARE>59</COD_FOND_FINANTARE>
    <DEN_FOND_FINANTARE>Programe finantate din FSE PLUS aferent cadrului financiar 2021-2027</DEN_FOND_FINANTARE>
    <DEN_SURSA>Total surse</DEN_SURSA>
    <COD_INDICATOR>5000</COD_INDICATOR>
    <DEN_INDICATOR>TOTAL GENERAL</DEN_INDICATOR>
    <CATEGORIE_RAND>I.  Credite de angajament</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>489605</PROGRAM_2025>
    <ESTIMARI_2026>997937</ESTIMARI_2026>
    <ESTIMARI_2027>1085480</ESTIMARI_2027>
    <ESTIMARI_2028>1121254</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>3694276</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROIECTULUI FINANTAT/PROPUS LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 3/04/01</ANEXA>
    <COD_ORDONATOR>21</COD_ORDONATOR>
    <DEN_ORDONATOR>Ministerul Muncii, Familiei, Tineretului si Solidaritatii Sociale</DEN_ORDONATOR>
    <CODFISCAL>11370190</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>110</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Programul operational Educatie si ocupare 2021-2027</DEN_PROGRAM_OPERATIONAL>
    <COD_PROIECT>23830</COD_PROIECT>
    <DEN_PROIECT>SMART SPO - Servicii moderne, accesibile si pregatite pentru viitor</DEN_PROIECT>
    <COD_FOND_FINANTARE>59</COD_FOND_FINANTARE>
    <DEN_FOND_FINANTARE>Programe finantate din FSE PLUS aferent cadrului financiar 2021-2027</DEN_FOND_FINANTARE>
    <DEN_SURSA>Total surse</DEN_SURSA>
    <COD_INDICATOR>5000</COD_INDICATOR>
    <DEN_INDICATOR>TOTAL GENERAL</DEN_INDICATOR>
    <CATEGORIE_RAND>II. Credite bugetare</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>489605</PROGRAM_2025>
    <ESTIMARI_2026>997937</ESTIMARI_2026>
    <ESTIMARI_2027>1085480</ESTIMARI_2027>
    <ESTIMARI_2028>1121254</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>3694276</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROIECTULUI FINANTAT/PROPUS LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 3/04/01</ANEXA>
    <COD_ORDONATOR>21</COD_ORDONATOR>
    <DEN_ORDONATOR>Ministerul Muncii, Familiei, Tineretului si Solidaritatii Sociale</DEN_ORDONATOR>
    <CODFISCAL>11370190</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>110</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Programul operational Educatie si ocupare 2021-2027</DEN_PROGRAM_OPERATIONAL>
    <COD_PROIECT>23830</COD_PROIECT>
    <DEN_PROIECT>SMART SPO - Servicii moderne, accesibile si pregatite pentru viitor</DEN_PROIECT>
    <COD_FOND_FINANTARE>59</COD_FOND_FINANTARE>
    <DEN_FOND_FINANTARE>Programe finantate din FSE PLUS aferent cadrului financiar 2021-2027</DEN_FOND_FINANTARE>
    <DEN_SURSA>Buget fond somaj</DEN_SURSA>
    <COD_INDICATOR>5004</COD_INDICATOR>
    <DEN_INDICATOR>BUGETUL ASIGURARILOR PENTRU SOMAJ</DEN_INDICATOR>
    <CATEGORIE_RAND>I.  Credite de angajament</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>489605</PROGRAM_2025>
    <ESTIMARI_2026>997937</ESTIMARI_2026>
    <ESTIMARI_2027>1085480</ESTIMARI_2027>
    <ESTIMARI_2028>1121254</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>3694276</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROIECTULUI FINANTAT/PROPUS LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 3/04/01</ANEXA>
    <COD_ORDONATOR>21</COD_ORDONATOR>
    <DEN_ORDONATOR>Ministerul Muncii, Familiei, Tineretului si Solidaritatii Sociale</DEN_ORDONATOR>
    <CODFISCAL>11370190</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>110</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Programul operational Educatie si ocupare 2021-2027</DEN_PROGRAM_OPERATIONAL>
    <COD_PROIECT>23830</COD_PROIECT>
    <DEN_PROIECT>SMART SPO - Servicii moderne, accesibile si pregatite pentru viitor</DEN_PROIECT>
    <COD_FOND_FINANTARE>59</COD_FOND_FINANTARE>
    <DEN_FOND_FINANTARE>Programe finantate din FSE PLUS aferent cadrului financiar 2021-2027</DEN_FOND_FINANTARE>
    <DEN_SURSA>Buget fond somaj</DEN_SURSA>
    <COD_INDICATOR>5004</COD_INDICATOR>
    <DEN_INDICATOR>BUGETUL ASIGURARILOR PENTRU SOMAJ</DEN_INDICATOR>
    <CATEGORIE_RAND>II. Credite bugetare</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>489605</PROGRAM_2025>
    <ESTIMARI_2026>997937</ESTIMARI_2026>
    <ESTIMARI_2027>1085480</ESTIMARI_2027>
    <ESTIMARI_2028>1121254</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>3694276</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROIECTULUI FINANTAT/PROPUS LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 3/04/01</ANEXA>
    <COD_ORDONATOR>21</COD_ORDONATOR>
    <DEN_ORDONATOR>Ministerul Muncii, Familiei, Tineretului si Solidaritatii Sociale</DEN_ORDONATOR>
    <CODFISCAL>11370190</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>110</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Programul operational Educatie si ocupare 2021-2027</DEN_PROGRAM_OPERATIONAL>
    <COD_PROIECT>23830</COD_PROIECT>
    <DEN_PROIECT>SMART SPO - Servicii moderne, accesibile si pregatite pentru viitor</DEN_PROIECT>
    <COD_FOND_FINANTARE>59</COD_FOND_FINANTARE>
    <DEN_FOND_FINANTARE>Programe finantate din FSE PLUS aferent cadrului financiar 2021-2027</DEN_FOND_FINANTARE>
    <DEN_SURSA>Buget fond somaj</DEN_SURSA>
    <COD_INDICATOR>8004</COD_INDICATOR>
    <DEN_INDICATOR>ACTIUNI GENERALE ECONOMICE, COMERCIALE  SI DE MUNCA</DEN_INDICATOR>
    <CATEGORIE_RAND>I.  Credite de angajament</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>489605</PROGRAM_2025>
    <ESTIMARI_2026>997937</ESTIMARI_2026>
    <ESTIMARI_2027>1085480</ESTIMARI_2027>
    <ESTIMARI_2028>1121254</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>3694276</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROIECTULUI FINANTAT/PROPUS LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 3/04/01</ANEXA>
    <COD_ORDONATOR>21</COD_ORDONATOR>
    <DEN_ORDONATOR>Ministerul Muncii, Familiei, Tineretului si Solidaritatii Sociale</DEN_ORDONATOR>
    <CODFISCAL>11370190</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>110</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Programul operational Educatie si ocupare 2021-2027</DEN_PROGRAM_OPERATIONAL>
    <COD_PROIECT>23830</COD_PROIECT>
    <DEN_PROIECT>SMART SPO - Servicii moderne, accesibile si pregatite pentru viitor</DEN_PROIECT>
    <COD_FOND_FINANTARE>59</COD_FOND_FINANTARE>
    <DEN_FOND_FINANTARE>Programe finantate din FSE PLUS aferent cadrului financiar 2021-2027</DEN_FOND_FINANTARE>
    <DEN_SURSA>Buget fond somaj</DEN_SURSA>
    <COD_INDICATOR>8004</COD_INDICATOR>
    <DEN_INDICATOR>ACTIUNI GENERALE ECONOMICE, COMERCIALE  SI DE MUNCA</DEN_INDICATOR>
    <CATEGORIE_RAND>II. Credite bugetare</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>489605</PROGRAM_2025>
    <ESTIMARI_2026>997937</ESTIMARI_2026>
    <ESTIMARI_2027>1085480</ESTIMARI_2027>
    <ESTIMARI_2028>1121254</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>3694276</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROIECTULUI FINANTAT/PROPUS LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 3/04/01</ANEXA>
    <COD_ORDONATOR>21</COD_ORDONATOR>
    <DEN_ORDONATOR>Ministerul Muncii, Familiei, Tineretului si Solidaritatii Sociale</DEN_ORDONATOR>
    <CODFISCAL>11370190</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>110</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Programul operational Educatie si ocupare 2021-2027</DEN_PROGRAM_OPERATIONAL>
    <COD_PROIECT>23830</COD_PROIECT>
    <DEN_PROIECT>SMART SPO - Servicii moderne, accesibile si pregatite pentru viitor</DEN_PROIECT>
    <COD_FOND_FINANTARE>59</COD_FOND_FINANTARE>
    <DEN_FOND_FINANTARE>Programe finantate din FSE PLUS aferent cadrului financiar 2021-2027</DEN_FOND_FINANTARE>
    <DEN_SURSA>Buget fond somaj</DEN_SURSA>
    <COD_INDICATOR>800456</COD_INDICATOR>
    <DEN_INDICATOR>TITLUL VIII PROIECTE CU FINANTARE DIN FONDURI EXTERNE NERAMBURSABILE &#40;FEN&#41; POSTADERARE</DEN_INDICATOR>
    <CATEGORIE_RAND>I.  Credite de angajament</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>489605</PROGRAM_2025>
    <ESTIMARI_2026>997937</ESTIMARI_2026>
    <ESTIMARI_2027>1085480</ESTIMARI_2027>
    <ESTIMARI_2028>1121254</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>3694276</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROIECTULUI FINANTAT/PROPUS LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 3/04/01</ANEXA>
    <COD_ORDONATOR>21</COD_ORDONATOR>
    <DEN_ORDONATOR>Ministerul Muncii, Familiei, Tineretului si Solidaritatii Sociale</DEN_ORDONATOR>
    <CODFISCAL>11370190</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>110</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Programul operational Educatie si ocupare 2021-2027</DEN_PROGRAM_OPERATIONAL>
    <COD_PROIECT>23830</COD_PROIECT>
    <DEN_PROIECT>SMART SPO - Servicii moderne, accesibile si pregatite pentru viitor</DEN_PROIECT>
    <COD_FOND_FINANTARE>59</COD_FOND_FINANTARE>
    <DEN_FOND_FINANTARE>Programe finantate din FSE PLUS aferent cadrului financiar 2021-2027</DEN_FOND_FINANTARE>
    <DEN_SURSA>Buget fond somaj</DEN_SURSA>
    <COD_INDICATOR>800456</COD_INDICATOR>
    <DEN_INDICATOR>TITLUL VIII PROIECTE CU FINANTARE DIN FONDURI EXTERNE NERAMBURSABILE &#40;FEN&#41; POSTADERARE</DEN_INDICATOR>
    <CATEGORIE_RAND>II. Credite bugetare</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>489605</PROGRAM_2025>
    <ESTIMARI_2026>997937</ESTIMARI_2026>
    <ESTIMARI_2027>1085480</ESTIMARI_2027>
    <ESTIMARI_2028>1121254</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>3694276</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROIECTULUI FINANTAT/PROPUS LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 3/04/01</ANEXA>
    <COD_ORDONATOR>21</COD_ORDONATOR>
    <DEN_ORDONATOR>Ministerul Muncii, Familiei, Tineretului si Solidaritatii Sociale</DEN_ORDONATOR>
    <CODFISCAL>11370190</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>110</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Programul operational Educatie si ocupare 2021-2027</DEN_PROGRAM_OPERATIONAL>
    <COD_PROIECT>23830</COD_PROIECT>
    <DEN_PROIECT>SMART SPO - Servicii moderne, accesibile si pregatite pentru viitor</DEN_PROIECT>
    <COD_FOND_FINANTARE>59</COD_FOND_FINANTARE>
    <DEN_FOND_FINANTARE>Programe finantate din FSE PLUS aferent cadrului financiar 2021-2027</DEN_FOND_FINANTARE>
    <DEN_SURSA>Buget fond somaj</DEN_SURSA>
    <COD_INDICATOR>80045649</COD_INDICATOR>
    <DEN_INDICATOR> Programe finantate din Fondul Social European Plus &#40;FSE+&#41;, aferente cadrului financiar 2021-2027</DEN_INDICATOR>
    <CATEGORIE_RAND>I.  Credite de angajament</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>489605</PROGRAM_2025>
    <ESTIMARI_2026>997937</ESTIMARI_2026>
    <ESTIMARI_2027>1085480</ESTIMARI_2027>
    <ESTIMARI_2028>1121254</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>3694276</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROIECTULUI FINANTAT/PROPUS LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 3/04/01</ANEXA>
    <COD_ORDONATOR>21</COD_ORDONATOR>
    <DEN_ORDONATOR>Ministerul Muncii, Familiei, Tineretului si Solidaritatii Sociale</DEN_ORDONATOR>
    <CODFISCAL>11370190</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>110</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Programul operational Educatie si ocupare 2021-2027</DEN_PROGRAM_OPERATIONAL>
    <COD_PROIECT>23830</COD_PROIECT>
    <DEN_PROIECT>SMART SPO - Servicii moderne, accesibile si pregatite pentru viitor</DEN_PROIECT>
    <COD_FOND_FINANTARE>59</COD_FOND_FINANTARE>
    <DEN_FOND_FINANTARE>Programe finantate din FSE PLUS aferent cadrului financiar 2021-2027</DEN_FOND_FINANTARE>
    <DEN_SURSA>Buget fond somaj</DEN_SURSA>
    <COD_INDICATOR>80045649</COD_INDICATOR>
    <DEN_INDICATOR> Programe finantate din Fondul Social European Plus &#40;FSE+&#41;, aferente cadrului financiar 2021-2027</DEN_INDICATOR>
    <CATEGORIE_RAND>II. Credite bugetare</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>489605</PROGRAM_2025>
    <ESTIMARI_2026>997937</ESTIMARI_2026>
    <ESTIMARI_2027>1085480</ESTIMARI_2027>
    <ESTIMARI_2028>1121254</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>3694276</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROIECTULUI FINANTAT/PROPUS LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 3/04/01</ANEXA>
    <COD_ORDONATOR>21</COD_ORDONATOR>
    <DEN_ORDONATOR>Ministerul Muncii, Familiei, Tineretului si Solidaritatii Sociale</DEN_ORDONATOR>
    <CODFISCAL>11370190</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>110</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Programul operational Educatie si ocupare 2021-2027</DEN_PROGRAM_OPERATIONAL>
    <COD_PROIECT>23830</COD_PROIECT>
    <DEN_PROIECT>SMART SPO - Servicii moderne, accesibile si pregatite pentru viitor</DEN_PROIECT>
    <COD_FOND_FINANTARE>59</COD_FOND_FINANTARE>
    <DEN_FOND_FINANTARE>Programe finantate din FSE PLUS aferent cadrului financiar 2021-2027</DEN_FOND_FINANTARE>
    <DEN_SURSA>Buget fond somaj</DEN_SURSA>
    <COD_INDICATOR>8004564901</COD_INDICATOR>
    <DEN_INDICATOR> Finantare nationala</DEN_INDICATOR>
    <CATEGORIE_RAND>I.  Credite de angajament</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>107713</PROGRAM_2025>
    <ESTIMARI_2026>183179</ESTIMARI_2026>
    <ESTIMARI_2027>238806</ESTIMARI_2027>
    <ESTIMARI_2028>250230</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>779928</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROIECTULUI FINANTAT/PROPUS LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 3/04/01</ANEXA>
    <COD_ORDONATOR>21</COD_ORDONATOR>
    <DEN_ORDONATOR>Ministerul Muncii, Familiei, Tineretului si Solidaritatii Sociale</DEN_ORDONATOR>
    <CODFISCAL>11370190</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>110</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Programul operational Educatie si ocupare 2021-2027</DEN_PROGRAM_OPERATIONAL>
    <COD_PROIECT>23830</COD_PROIECT>
    <DEN_PROIECT>SMART SPO - Servicii moderne, accesibile si pregatite pentru viitor</DEN_PROIECT>
    <COD_FOND_FINANTARE>59</COD_FOND_FINANTARE>
    <DEN_FOND_FINANTARE>Programe finantate din FSE PLUS aferent cadrului financiar 2021-2027</DEN_FOND_FINANTARE>
    <DEN_SURSA>Buget fond somaj</DEN_SURSA>
    <COD_INDICATOR>8004564901</COD_INDICATOR>
    <DEN_INDICATOR> Finantare nationala</DEN_INDICATOR>
    <CATEGORIE_RAND>II. Credite bugetare</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>107713</PROGRAM_2025>
    <ESTIMARI_2026>183179</ESTIMARI_2026>
    <ESTIMARI_2027>238806</ESTIMARI_2027>
    <ESTIMARI_2028>250230</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>779928</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROIECTULUI FINANTAT/PROPUS LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 3/04/01</ANEXA>
    <COD_ORDONATOR>21</COD_ORDONATOR>
    <DEN_ORDONATOR>Ministerul Muncii, Familiei, Tineretului si Solidaritatii Sociale</DEN_ORDONATOR>
    <CODFISCAL>11370190</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>110</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Programul operational Educatie si ocupare 2021-2027</DEN_PROGRAM_OPERATIONAL>
    <COD_PROIECT>23830</COD_PROIECT>
    <DEN_PROIECT>SMART SPO - Servicii moderne, accesibile si pregatite pentru viitor</DEN_PROIECT>
    <COD_FOND_FINANTARE>59</COD_FOND_FINANTARE>
    <DEN_FOND_FINANTARE>Programe finantate din FSE PLUS aferent cadrului financiar 2021-2027</DEN_FOND_FINANTARE>
    <DEN_SURSA>Buget fond somaj</DEN_SURSA>
    <COD_INDICATOR>8004564902</COD_INDICATOR>
    <DEN_INDICATOR> Finantare externa nerambursabila</DEN_INDICATOR>
    <CATEGORIE_RAND>I.  Credite de angajament</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>381892</PROGRAM_2025>
    <ESTIMARI_2026>814758</ESTIMARI_2026>
    <ESTIMARI_2027>846674</ESTIMARI_2027>
    <ESTIMARI_2028>871024</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>2914348</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROIECTULUI FINANTAT/PROPUS LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 3/04/01</ANEXA>
    <COD_ORDONATOR>21</COD_ORDONATOR>
    <DEN_ORDONATOR>Ministerul Muncii, Familiei, Tineretului si Solidaritatii Sociale</DEN_ORDONATOR>
    <CODFISCAL>11370190</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>110</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Programul operational Educatie si ocupare 2021-2027</DEN_PROGRAM_OPERATIONAL>
    <COD_PROIECT>23830</COD_PROIECT>
    <DEN_PROIECT>SMART SPO - Servicii moderne, accesibile si pregatite pentru viitor</DEN_PROIECT>
    <COD_FOND_FINANTARE>59</COD_FOND_FINANTARE>
    <DEN_FOND_FINANTARE>Programe finantate din FSE PLUS aferent cadrului financiar 2021-2027</DEN_FOND_FINANTARE>
    <DEN_SURSA>Buget fond somaj</DEN_SURSA>
    <COD_INDICATOR>8004564902</COD_INDICATOR>
    <DEN_INDICATOR> Finantare externa nerambursabila</DEN_INDICATOR>
    <CATEGORIE_RAND>II. Credite bugetare</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>381892</PROGRAM_2025>
    <ESTIMARI_2026>814758</ESTIMARI_2026>
    <ESTIMARI_2027>846674</ESTIMARI_2027>
    <ESTIMARI_2028>871024</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>2914348</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROIECTULUI FINANTAT/PROPUS LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 3/04/01</ANEXA>
    <COD_ORDONATOR>21</COD_ORDONATOR>
    <DEN_ORDONATOR>Ministerul Muncii, Familiei, Tineretului si Solidaritatii Sociale</DEN_ORDONATOR>
    <CODFISCAL>11370190</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>110</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Programul operational Educatie si ocupare 2021-2027</DEN_PROGRAM_OPERATIONAL>
    <COD_PROIECT>25405</COD_PROIECT>
    <DEN_PROIECT>Angajatii au Multiple Posibilitati prin Formare Moderna - Cod MySMIS 313073</DEN_PROIECT>
    <COD_FOND_FINANTARE>59</COD_FOND_FINANTARE>
    <DEN_FOND_FINANTARE>Programe finantate din FSE PLUS aferent cadrului financiar 2021-2027</DEN_FOND_FINANTARE>
    <DEN_SURSA>Total surse</DEN_SURSA>
    <COD_INDICATOR>5000</COD_INDICATOR>
    <DEN_INDICATOR>TOTAL GENERAL</DEN_INDICATOR>
    <CATEGORIE_RAND>I.  Credite de angajament</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>263</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>773</PROGRAM_2025>
    <ESTIMARI_2026>759</ESTIMARI_2026>
    <ESTIMARI_2027>397</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>2192</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROIECTULUI FINANTAT/PROPUS LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 3/04/01</ANEXA>
    <COD_ORDONATOR>21</COD_ORDONATOR>
    <DEN_ORDONATOR>Ministerul Muncii, Familiei, Tineretului si Solidaritatii Sociale</DEN_ORDONATOR>
    <CODFISCAL>11370190</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>110</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Programul operational Educatie si ocupare 2021-2027</DEN_PROGRAM_OPERATIONAL>
    <COD_PROIECT>25405</COD_PROIECT>
    <DEN_PROIECT>Angajatii au Multiple Posibilitati prin Formare Moderna - Cod MySMIS 313073</DEN_PROIECT>
    <COD_FOND_FINANTARE>59</COD_FOND_FINANTARE>
    <DEN_FOND_FINANTARE>Programe finantate din FSE PLUS aferent cadrului financiar 2021-2027</DEN_FOND_FINANTARE>
    <DEN_SURSA>Total surse</DEN_SURSA>
    <COD_INDICATOR>5000</COD_INDICATOR>
    <DEN_INDICATOR>TOTAL GENERAL</DEN_INDICATOR>
    <CATEGORIE_RAND>II. Credite bugetare</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>263</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>773</PROGRAM_2025>
    <ESTIMARI_2026>759</ESTIMARI_2026>
    <ESTIMARI_2027>397</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>2192</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROIECTULUI FINANTAT/PROPUS LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 3/04/01</ANEXA>
    <COD_ORDONATOR>21</COD_ORDONATOR>
    <DEN_ORDONATOR>Ministerul Muncii, Familiei, Tineretului si Solidaritatii Sociale</DEN_ORDONATOR>
    <CODFISCAL>11370190</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>110</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Programul operational Educatie si ocupare 2021-2027</DEN_PROGRAM_OPERATIONAL>
    <COD_PROIECT>25405</COD_PROIECT>
    <DEN_PROIECT>Angajatii au Multiple Posibilitati prin Formare Moderna - Cod MySMIS 313073</DEN_PROIECT>
    <COD_FOND_FINANTARE>59</COD_FOND_FINANTARE>
    <DEN_FOND_FINANTARE>Programe finantate din FSE PLUS aferent cadrului financiar 2021-2027</DEN_FOND_FINANTARE>
    <DEN_SURSA>Buget fond somaj</DEN_SURSA>
    <COD_INDICATOR>5004</COD_INDICATOR>
    <DEN_INDICATOR>BUGETUL ASIGURARILOR PENTRU SOMAJ</DEN_INDICATOR>
    <CATEGORIE_RAND>I.  Credite de angajament</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>263</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>773</PROGRAM_2025>
    <ESTIMARI_2026>759</ESTIMARI_2026>
    <ESTIMARI_2027>397</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>2192</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROIECTULUI FINANTAT/PROPUS LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 3/04/01</ANEXA>
    <COD_ORDONATOR>21</COD_ORDONATOR>
    <DEN_ORDONATOR>Ministerul Muncii, Familiei, Tineretului si Solidaritatii Sociale</DEN_ORDONATOR>
    <CODFISCAL>11370190</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>110</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Programul operational Educatie si ocupare 2021-2027</DEN_PROGRAM_OPERATIONAL>
    <COD_PROIECT>25405</COD_PROIECT>
    <DEN_PROIECT>Angajatii au Multiple Posibilitati prin Formare Moderna - Cod MySMIS 313073</DEN_PROIECT>
    <COD_FOND_FINANTARE>59</COD_FOND_FINANTARE>
    <DEN_FOND_FINANTARE>Programe finantate din FSE PLUS aferent cadrului financiar 2021-2027</DEN_FOND_FINANTARE>
    <DEN_SURSA>Buget fond somaj</DEN_SURSA>
    <COD_INDICATOR>5004</COD_INDICATOR>
    <DEN_INDICATOR>BUGETUL ASIGURARILOR PENTRU SOMAJ</DEN_INDICATOR>
    <CATEGORIE_RAND>II. Credite bugetare</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>263</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>773</PROGRAM_2025>
    <ESTIMARI_2026>759</ESTIMARI_2026>
    <ESTIMARI_2027>397</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>2192</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROIECTULUI FINANTAT/PROPUS LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 3/04/01</ANEXA>
    <COD_ORDONATOR>21</COD_ORDONATOR>
    <DEN_ORDONATOR>Ministerul Muncii, Familiei, Tineretului si Solidaritatii Sociale</DEN_ORDONATOR>
    <CODFISCAL>11370190</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>110</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Programul operational Educatie si ocupare 2021-2027</DEN_PROGRAM_OPERATIONAL>
    <COD_PROIECT>25405</COD_PROIECT>