<?xml version="1.0" ?>
<!DOCTYPE main [
  <!ELEMENT main (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (TITLU_RAPORT?,ANEXA?,COD_ORDONATOR?,DEN_ORDONATOR?,CODFISCAL?,COD_PROGRAM_OPERATIONAL?,DEN_PROGRAM_OPERATIONAL?,COD_PROIECT?,DEN_PROIECT?,COD_FOND_FINANTARE?,DEN_FOND_FINANTARE?,DEN_SURSA?,ORDINE_AFISARE?,COD_INDICATOR?,DEN_INDICATOR?,CATEGORIE_RAND?,REALIZARI_PANA_IN_2022?,REALIZARI_2023?,EXECUTIE_PRELIMINATA_2024?,PROGRAM_2025?,ESTIMARI_2026?,ESTIMARI_2027?,ESTIMARI_2028?,ANII_URMATORI?,TOTAL?)+>
  <!ELEMENT TITLU_RAPORT (#PCDATA)>
  <!ELEMENT ANEXA (#PCDATA)>
  <!ELEMENT COD_ORDONATOR (#PCDATA)>
  <!ELEMENT DEN_ORDONATOR (#PCDATA)>
  <!ELEMENT CODFISCAL (#PCDATA)>
  <!ELEMENT COD_PROGRAM_OPERATIONAL (#PCDATA)>
  <!ELEMENT DEN_PROGRAM_OPERATIONAL (#PCDATA)>
  <!ELEMENT COD_PROIECT (#PCDATA)>
  <!ELEMENT DEN_PROIECT (#PCDATA)>
  <!ELEMENT COD_FOND_FINANTARE (#PCDATA)>
  <!ELEMENT DEN_FOND_FINANTARE (#PCDATA)>
  <!ELEMENT DEN_SURSA (#PCDATA)>
  <!ELEMENT ORDINE_AFISARE (#PCDATA)>
  <!ELEMENT COD_INDICATOR (#PCDATA)>
  <!ELEMENT DEN_INDICATOR (#PCDATA)>
  <!ELEMENT CATEGORIE_RAND (#PCDATA)>
  <!ELEMENT REALIZARI_PANA_IN_2022 (#PCDATA)>
  <!ELEMENT REALIZARI_2023 (#PCDATA)>
  <!ELEMENT EXECUTIE_PRELIMINATA_2024 (#PCDATA)>
  <!ELEMENT PROGRAM_2025 (#PCDATA)>
  <!ELEMENT ESTIMARI_2026 (#PCDATA)>
  <!ELEMENT ESTIMARI_2027 (#PCDATA)>
  <!ELEMENT ESTIMARI_2028 (#PCDATA)>
  <!ELEMENT ANII_URMATORI (#PCDATA)>
  <!ELEMENT TOTAL (#PCDATA)>
]>
<main>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROIECTULUI FINANTAT/PROPUS LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 10/05</ANEXA>
    <COD_ORDONATOR>01</COD_ORDONATOR>
    <DEN_ORDONATOR>Casa Nationala de Asigurari de Sanatate</DEN_ORDONATOR>
    <CODFISCAL>11697800</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>109</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Programul operational Sanatate 2021-2027</DEN_PROGRAM_OPERATIONAL>
    <COD_PROIECT>22238</COD_PROIECT>
    <DEN_PROIECT>Romanian ePrescription for Cross-Border e-Health &#40;ROEP&#41;</DEN_PROIECT>
    <COD_FOND_FINANTARE>64</COD_FOND_FINANTARE>
    <DEN_FOND_FINANTARE>Alte programe comunitare finantate in perioada 2021-2027</DEN_FOND_FINANTARE>
    <DEN_SURSA>Total surse</DEN_SURSA>
    <ORDINE_AFISARE>270</ORDINE_AFISARE>
    <COD_INDICATOR>5000</COD_INDICATOR>
    <DEN_INDICATOR>TOTAL GENERAL</DEN_INDICATOR>
    <CATEGORIE_RAND>I.  Credite de angajament</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>9730</PROGRAM_2025>
    <ESTIMARI_2026>650</ESTIMARI_2026>
    <ESTIMARI_2027>991</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>11371</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROIECTULUI FINANTAT/PROPUS LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 10/05</ANEXA>
    <COD_ORDONATOR>01</COD_ORDONATOR>
    <DEN_ORDONATOR>Casa Nationala de Asigurari de Sanatate</DEN_ORDONATOR>
    <CODFISCAL>11697800</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>109</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Programul operational Sanatate 2021-2027</DEN_PROGRAM_OPERATIONAL>
    <COD_PROIECT>22238</COD_PROIECT>
    <DEN_PROIECT>Romanian ePrescription for Cross-Border e-Health &#40;ROEP&#41;</DEN_PROIECT>
    <COD_FOND_FINANTARE>64</COD_FOND_FINANTARE>
    <DEN_FOND_FINANTARE>Alte programe comunitare finantate in perioada 2021-2027</DEN_FOND_FINANTARE>
    <DEN_SURSA>Total surse</DEN_SURSA>
    <ORDINE_AFISARE>270</ORDINE_AFISARE>
    <COD_INDICATOR>5000</COD_INDICATOR>
    <DEN_INDICATOR>TOTAL GENERAL</DEN_INDICATOR>
    <CATEGORIE_RAND>II. Credite bugetare</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>5800</PROGRAM_2025>
    <ESTIMARI_2026>3350</ESTIMARI_2026>
    <ESTIMARI_2027>2221</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>11371</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROIECTULUI FINANTAT/PROPUS LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 10/05</ANEXA>
    <COD_ORDONATOR>01</COD_ORDONATOR>
    <DEN_ORDONATOR>Casa Nationala de Asigurari de Sanatate</DEN_ORDONATOR>
    <CODFISCAL>11697800</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>109</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Programul operational Sanatate 2021-2027</DEN_PROGRAM_OPERATIONAL>
    <COD_PROIECT>22238</COD_PROIECT>
    <DEN_PROIECT>Romanian ePrescription for Cross-Border e-Health &#40;ROEP&#41;</DEN_PROIECT>
    <COD_FOND_FINANTARE>64</COD_FOND_FINANTARE>
    <DEN_FOND_FINANTARE>Alte programe comunitare finantate in perioada 2021-2027</DEN_FOND_FINANTARE>
    <DEN_SURSA>Buget fond sanatate</DEN_SURSA>
    <ORDINE_AFISARE>271</ORDINE_AFISARE>
    <COD_INDICATOR>5005</COD_INDICATOR>
    <DEN_INDICATOR>CHELTUIELI - TOTAL</DEN_INDICATOR>
    <CATEGORIE_RAND>I.  Credite de angajament</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>6072</PROGRAM_2025>
    <ESTIMARI_2026>406</ESTIMARI_2026>
    <ESTIMARI_2027>625</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>7103</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROIECTULUI FINANTAT/PROPUS LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 10/05</ANEXA>
    <COD_ORDONATOR>01</COD_ORDONATOR>
    <DEN_ORDONATOR>Casa Nationala de Asigurari de Sanatate</DEN_ORDONATOR>
    <CODFISCAL>11697800</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>109</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Programul operational Sanatate 2021-2027</DEN_PROGRAM_OPERATIONAL>
    <COD_PROIECT>22238</COD_PROIECT>
    <DEN_PROIECT>Romanian ePrescription for Cross-Border e-Health &#40;ROEP&#41;</DEN_PROIECT>
    <COD_FOND_FINANTARE>64</COD_FOND_FINANTARE>
    <DEN_FOND_FINANTARE>Alte programe comunitare finantate in perioada 2021-2027</DEN_FOND_FINANTARE>
    <DEN_SURSA>Buget fond sanatate</DEN_SURSA>
    <ORDINE_AFISARE>271</ORDINE_AFISARE>
    <COD_INDICATOR>5005</COD_INDICATOR>
    <DEN_INDICATOR>CHELTUIELI - TOTAL</DEN_INDICATOR>
    <CATEGORIE_RAND>II. Credite bugetare</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>3620</PROGRAM_2025>
    <ESTIMARI_2026>2090</ESTIMARI_2026>
    <ESTIMARI_2027>1393</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>7103</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROIECTULUI FINANTAT/PROPUS LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 10/05</ANEXA>
    <COD_ORDONATOR>01</COD_ORDONATOR>
    <DEN_ORDONATOR>Casa Nationala de Asigurari de Sanatate</DEN_ORDONATOR>
    <CODFISCAL>11697800</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>109</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Programul operational Sanatate 2021-2027</DEN_PROGRAM_OPERATIONAL>
    <COD_PROIECT>22238</COD_PROIECT>
    <DEN_PROIECT>Romanian ePrescription for Cross-Border e-Health &#40;ROEP&#41;</DEN_PROIECT>
    <COD_FOND_FINANTARE>64</COD_FOND_FINANTARE>
    <DEN_FOND_FINANTARE>Alte programe comunitare finantate in perioada 2021-2027</DEN_FOND_FINANTARE>
    <DEN_SURSA>Fonduri externe nerambursabile</DEN_SURSA>
    <ORDINE_AFISARE>277</ORDINE_AFISARE>
    <COD_INDICATOR>5008</COD_INDICATOR>
    <DEN_INDICATOR>FONDURI EXTERNE NERAMBURSABILE</DEN_INDICATOR>
    <CATEGORIE_RAND>I.  Credite de angajament</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>3658</PROGRAM_2025>
    <ESTIMARI_2026>244</ESTIMARI_2026>
    <ESTIMARI_2027>366</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>4268</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROIECTULUI FINANTAT/PROPUS LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 10/05</ANEXA>
    <COD_ORDONATOR>01</COD_ORDONATOR>
    <DEN_ORDONATOR>Casa Nationala de Asigurari de Sanatate</DEN_ORDONATOR>
    <CODFISCAL>11697800</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>109</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Programul operational Sanatate 2021-2027</DEN_PROGRAM_OPERATIONAL>
    <COD_PROIECT>22238</COD_PROIECT>
    <DEN_PROIECT>Romanian ePrescription for Cross-Border e-Health &#40;ROEP&#41;</DEN_PROIECT>
    <COD_FOND_FINANTARE>64</COD_FOND_FINANTARE>
    <DEN_FOND_FINANTARE>Alte programe comunitare finantate in perioada 2021-2027</DEN_FOND_FINANTARE>
    <DEN_SURSA>Fonduri externe nerambursabile</DEN_SURSA>
    <ORDINE_AFISARE>277</ORDINE_AFISARE>
    <COD_INDICATOR>5008</COD_INDICATOR>
    <DEN_INDICATOR>FONDURI EXTERNE NERAMBURSABILE</DEN_INDICATOR>
    <CATEGORIE_RAND>II. Credite bugetare</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>2180</PROGRAM_2025>
    <ESTIMARI_2026>1260</ESTIMARI_2026>
    <ESTIMARI_2027>828</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>4268</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROIECTULUI FINANTAT/PROPUS LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 10/05</ANEXA>
    <COD_ORDONATOR>01</COD_ORDONATOR>
    <DEN_ORDONATOR>Casa Nationala de Asigurari de Sanatate</DEN_ORDONATOR>
    <CODFISCAL>11697800</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>109</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Programul operational Sanatate 2021-2027</DEN_PROGRAM_OPERATIONAL>
    <COD_PROIECT>22238</COD_PROIECT>
    <DEN_PROIECT>Romanian ePrescription for Cross-Border e-Health &#40;ROEP&#41;</DEN_PROIECT>
    <COD_FOND_FINANTARE>64</COD_FOND_FINANTARE>
    <DEN_FOND_FINANTARE>Alte programe comunitare finantate in perioada 2021-2027</DEN_FOND_FINANTARE>
    <DEN_SURSA>Buget fond sanatate</DEN_SURSA>
    <ORDINE_AFISARE>272</ORDINE_AFISARE>
    <COD_INDICATOR>6605</COD_INDICATOR>
    <DEN_INDICATOR>SANATATE</DEN_INDICATOR>
    <CATEGORIE_RAND>I.  Credite de angajament</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>6072</PROGRAM_2025>
    <ESTIMARI_2026>406</ESTIMARI_2026>
    <ESTIMARI_2027>625</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>7103</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROIECTULUI FINANTAT/PROPUS LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 10/05</ANEXA>
    <COD_ORDONATOR>01</COD_ORDONATOR>
    <DEN_ORDONATOR>Casa Nationala de Asigurari de Sanatate</DEN_ORDONATOR>
    <CODFISCAL>11697800</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>109</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Programul operational Sanatate 2021-2027</DEN_PROGRAM_OPERATIONAL>
    <COD_PROIECT>22238</COD_PROIECT>
    <DEN_PROIECT>Romanian ePrescription for Cross-Border e-Health &#40;ROEP&#41;</DEN_PROIECT>
    <COD_FOND_FINANTARE>64</COD_FOND_FINANTARE>
    <DEN_FOND_FINANTARE>Alte programe comunitare finantate in perioada 2021-2027</DEN_FOND_FINANTARE>
    <DEN_SURSA>Buget fond sanatate</DEN_SURSA>
    <ORDINE_AFISARE>272</ORDINE_AFISARE>
    <COD_INDICATOR>6605</COD_INDICATOR>
    <DEN_INDICATOR>SANATATE</DEN_INDICATOR>
    <CATEGORIE_RAND>II. Credite bugetare</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>3620</PROGRAM_2025>
    <ESTIMARI_2026>2090</ESTIMARI_2026>
    <ESTIMARI_2027>1393</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>7103</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROIECTULUI FINANTAT/PROPUS LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 10/05</ANEXA>
    <COD_ORDONATOR>01</COD_ORDONATOR>
    <DEN_ORDONATOR>Casa Nationala de Asigurari de Sanatate</DEN_ORDONATOR>
    <CODFISCAL>11697800</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>109</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Programul operational Sanatate 2021-2027</DEN_PROGRAM_OPERATIONAL>
    <COD_PROIECT>22238</COD_PROIECT>
    <DEN_PROIECT>Romanian ePrescription for Cross-Border e-Health &#40;ROEP&#41;</DEN_PROIECT>
    <COD_FOND_FINANTARE>64</COD_FOND_FINANTARE>
    <DEN_FOND_FINANTARE>Alte programe comunitare finantate in perioada 2021-2027</DEN_FOND_FINANTARE>
    <DEN_SURSA>Buget fond sanatate</DEN_SURSA>
    <ORDINE_AFISARE>273</ORDINE_AFISARE>
    <COD_INDICATOR>660556</COD_INDICATOR>
    <DEN_INDICATOR>TITLUL VIII PROIECTE CU FINANTARE DIN FONDURI EXTERNE NERAMBURSABILE &#40;FEN&#41; POSTADERARE</DEN_INDICATOR>
    <CATEGORIE_RAND>I.  Credite de angajament</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>6072</PROGRAM_2025>
    <ESTIMARI_2026>406</ESTIMARI_2026>
    <ESTIMARI_2027>625</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>7103</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROIECTULUI FINANTAT/PROPUS LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 10/05</ANEXA>
    <COD_ORDONATOR>01</COD_ORDONATOR>
    <DEN_ORDONATOR>Casa Nationala de Asigurari de Sanatate</DEN_ORDONATOR>
    <CODFISCAL>11697800</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>109</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Programul operational Sanatate 2021-2027</DEN_PROGRAM_OPERATIONAL>
    <COD_PROIECT>22238</COD_PROIECT>
    <DEN_PROIECT>Romanian ePrescription for Cross-Border e-Health &#40;ROEP&#41;</DEN_PROIECT>
    <COD_FOND_FINANTARE>64</COD_FOND_FINANTARE>
    <DEN_FOND_FINANTARE>Alte programe comunitare finantate in perioada 2021-2027</DEN_FOND_FINANTARE>
    <DEN_SURSA>Buget fond sanatate</DEN_SURSA>
    <ORDINE_AFISARE>273</ORDINE_AFISARE>
    <COD_INDICATOR>660556</COD_INDICATOR>
    <DEN_INDICATOR>TITLUL VIII PROIECTE CU FINANTARE DIN FONDURI EXTERNE NERAMBURSABILE &#40;FEN&#41; POSTADERARE</DEN_INDICATOR>
    <CATEGORIE_RAND>II. Credite bugetare</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>3620</PROGRAM_2025>
    <ESTIMARI_2026>2090</ESTIMARI_2026>
    <ESTIMARI_2027>1393</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>7103</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROIECTULUI FINANTAT/PROPUS LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 10/05</ANEXA>
    <COD_ORDONATOR>01</COD_ORDONATOR>
    <DEN_ORDONATOR>Casa Nationala de Asigurari de Sanatate</DEN_ORDONATOR>
    <CODFISCAL>11697800</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>109</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Programul operational Sanatate 2021-2027</DEN_PROGRAM_OPERATIONAL>
    <COD_PROIECT>22238</COD_PROIECT>
    <DEN_PROIECT>Romanian ePrescription for Cross-Border e-Health &#40;ROEP&#41;</DEN_PROIECT>
    <COD_FOND_FINANTARE>64</COD_FOND_FINANTARE>
    <DEN_FOND_FINANTARE>Alte programe comunitare finantate in perioada 2021-2027</DEN_FOND_FINANTARE>
    <DEN_SURSA>Buget fond sanatate</DEN_SURSA>
    <ORDINE_AFISARE>274</ORDINE_AFISARE>
    <COD_INDICATOR>66055672</COD_INDICATOR>
    <DEN_INDICATOR>Alte programe comunitare finantate in perioada 2021-2027</DEN_INDICATOR>
    <CATEGORIE_RAND>I.  Credite de angajament</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>6072</PROGRAM_2025>
    <ESTIMARI_2026>406</ESTIMARI_2026>
    <ESTIMARI_2027>625</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>7103</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROIECTULUI FINANTAT/PROPUS LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 10/05</ANEXA>
    <COD_ORDONATOR>01</COD_ORDONATOR>
    <DEN_ORDONATOR>Casa Nationala de Asigurari de Sanatate</DEN_ORDONATOR>
    <CODFISCAL>11697800</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>109</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Programul operational Sanatate 2021-2027</DEN_PROGRAM_OPERATIONAL>
    <COD_PROIECT>22238</COD_PROIECT>
    <DEN_PROIECT>Romanian ePrescription for Cross-Border e-Health &#40;ROEP&#41;</DEN_PROIECT>
    <COD_FOND_FINANTARE>64</COD_FOND_FINANTARE>
    <DEN_FOND_FINANTARE>Alte programe comunitare finantate in perioada 2021-2027</DEN_FOND_FINANTARE>
    <DEN_SURSA>Buget fond sanatate</DEN_SURSA>
    <ORDINE_AFISARE>274</ORDINE_AFISARE>
    <COD_INDICATOR>66055672</COD_INDICATOR>
    <DEN_INDICATOR>Alte programe comunitare finantate in perioada 2021-2027</DEN_INDICATOR>
    <CATEGORIE_RAND>II. Credite bugetare</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>3620</PROGRAM_2025>
    <ESTIMARI_2026>2090</ESTIMARI_2026>
    <ESTIMARI_2027>1393</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>7103</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROIECTULUI FINANTAT/PROPUS LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 10/05</ANEXA>
    <COD_ORDONATOR>01</COD_ORDONATOR>
    <DEN_ORDONATOR>Casa Nationala de Asigurari de Sanatate</DEN_ORDONATOR>
    <CODFISCAL>11697800</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>109</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Programul operational Sanatate 2021-2027</DEN_PROGRAM_OPERATIONAL>
    <COD_PROIECT>22238</COD_PROIECT>
    <DEN_PROIECT>Romanian ePrescription for Cross-Border e-Health &#40;ROEP&#41;</DEN_PROIECT>
    <COD_FOND_FINANTARE>64</COD_FOND_FINANTARE>
    <DEN_FOND_FINANTARE>Alte programe comunitare finantate in perioada 2021-2027</DEN_FOND_FINANTARE>
    <DEN_SURSA>Buget fond sanatate</DEN_SURSA>
    <ORDINE_AFISARE>275</ORDINE_AFISARE>
    <COD_INDICATOR>6605567201</COD_INDICATOR>
    <DEN_INDICATOR>Finantare nationala</DEN_INDICATOR>
    <CATEGORIE_RAND>I.  Credite de angajament</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>1946</PROGRAM_2025>
    <ESTIMARI_2026>130</ESTIMARI_2026>
    <ESTIMARI_2027>198</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>2274</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROIECTULUI FINANTAT/PROPUS LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 10/05</ANEXA>
    <COD_ORDONATOR>01</COD_ORDONATOR>
    <DEN_ORDONATOR>Casa Nationala de Asigurari de Sanatate</DEN_ORDONATOR>
    <CODFISCAL>11697800</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>109</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Programul operational Sanatate 2021-2027</DEN_PROGRAM_OPERATIONAL>
    <COD_PROIECT>22238</COD_PROIECT>
    <DEN_PROIECT>Romanian ePrescription for Cross-Border e-Health &#40;ROEP&#41;</DEN_PROIECT>
    <COD_FOND_FINANTARE>64</COD_FOND_FINANTARE>
    <DEN_FOND_FINANTARE>Alte programe comunitare finantate in perioada 2021-2027</DEN_FOND_FINANTARE>
    <DEN_SURSA>Buget fond sanatate</DEN_SURSA>
    <ORDINE_AFISARE>275</ORDINE_AFISARE>
    <COD_INDICATOR>6605567201</COD_INDICATOR>
    <DEN_INDICATOR>Finantare nationala</DEN_INDICATOR>
    <CATEGORIE_RAND>II. Credite bugetare</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>1160</PROGRAM_2025>
    <ESTIMARI_2026>670</ESTIMARI_2026>
    <ESTIMARI_2027>444</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>2274</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROIECTULUI FINANTAT/PROPUS LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 10/05</ANEXA>
    <COD_ORDONATOR>01</COD_ORDONATOR>
    <DEN_ORDONATOR>Casa Nationala de Asigurari de Sanatate</DEN_ORDONATOR>
    <CODFISCAL>11697800</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>109</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Programul operational Sanatate 2021-2027</DEN_PROGRAM_OPERATIONAL>
    <COD_PROIECT>22238</COD_PROIECT>
    <DEN_PROIECT>Romanian ePrescription for Cross-Border e-Health &#40;ROEP&#41;</DEN_PROIECT>
    <COD_FOND_FINANTARE>64</COD_FOND_FINANTARE>
    <DEN_FOND_FINANTARE>Alte programe comunitare finantate in perioada 2021-2027</DEN_FOND_FINANTARE>
    <DEN_SURSA>Buget fond sanatate</DEN_SURSA>
    <ORDINE_AFISARE>276</ORDINE_AFISARE>
    <COD_INDICATOR>6605567202</COD_INDICATOR>
    <DEN_INDICATOR>Finantare externa nerambursabila</DEN_INDICATOR>
    <CATEGORIE_RAND>I.  Credite de angajament</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>4126</PROGRAM_2025>
    <ESTIMARI_2026>276</ESTIMARI_2026>
    <ESTIMARI_2027>427</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>4829</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROIECTULUI FINANTAT/PROPUS LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 10/05</ANEXA>
    <COD_ORDONATOR>01</COD_ORDONATOR>
    <DEN_ORDONATOR>Casa Nationala de Asigurari de Sanatate</DEN_ORDONATOR>
    <CODFISCAL>11697800</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>109</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Programul operational Sanatate 2021-2027</DEN_PROGRAM_OPERATIONAL>
    <COD_PROIECT>22238</COD_PROIECT>
    <DEN_PROIECT>Romanian ePrescription for Cross-Border e-Health &#40;ROEP&#41;</DEN_PROIECT>
    <COD_FOND_FINANTARE>64</COD_FOND_FINANTARE>
    <DEN_FOND_FINANTARE>Alte programe comunitare finantate in perioada 2021-2027</DEN_FOND_FINANTARE>
    <DEN_SURSA>Buget fond sanatate</DEN_SURSA>
    <ORDINE_AFISARE>276</ORDINE_AFISARE>
    <COD_INDICATOR>6605567202</COD_INDICATOR>
    <DEN_INDICATOR>Finantare externa nerambursabila</DEN_INDICATOR>
    <CATEGORIE_RAND>II. Credite bugetare</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>2460</PROGRAM_2025>
    <ESTIMARI_2026>1420</ESTIMARI_2026>
    <ESTIMARI_2027>949</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>4829</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROIECTULUI FINANTAT/PROPUS LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 10/05</ANEXA>
    <COD_ORDONATOR>01</COD_ORDONATOR>
    <DEN_ORDONATOR>Casa Nationala de Asigurari de Sanatate</DEN_ORDONATOR>
    <CODFISCAL>11697800</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>109</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Programul operational Sanatate 2021-2027</DEN_PROGRAM_OPERATIONAL>
    <COD_PROIECT>22238</COD_PROIECT>
    <DEN_PROIECT>Romanian ePrescription for Cross-Border e-Health &#40;ROEP&#41;</DEN_PROIECT>
    <COD_FOND_FINANTARE>64</COD_FOND_FINANTARE>
    <DEN_FOND_FINANTARE>Alte programe comunitare finantate in perioada 2021-2027</DEN_FOND_FINANTARE>
    <DEN_SURSA>Fonduri externe nerambursabile</DEN_SURSA>
    <ORDINE_AFISARE>278</ORDINE_AFISARE>
    <COD_INDICATOR>6608</COD_INDICATOR>
    <DEN_INDICATOR>SANATATE</DEN_INDICATOR>
    <CATEGORIE_RAND>I.  Credite de angajament</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>3658</PROGRAM_2025>
    <ESTIMARI_2026>244</ESTIMARI_2026>
    <ESTIMARI_2027>366</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>4268</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROIECTULUI FINANTAT/PROPUS LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 10/05</ANEXA>
    <COD_ORDONATOR>01</COD_ORDONATOR>
    <DEN_ORDONATOR>Casa Nationala de Asigurari de Sanatate</DEN_ORDONATOR>
    <CODFISCAL>11697800</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>109</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Programul operational Sanatate 2021-2027</DEN_PROGRAM_OPERATIONAL>
    <COD_PROIECT>22238</COD_PROIECT>
    <DEN_PROIECT>Romanian ePrescription for Cross-Border e-Health &#40;ROEP&#41;</DEN_PROIECT>
    <COD_FOND_FINANTARE>64</COD_FOND_FINANTARE>
    <DEN_FOND_FINANTARE>Alte programe comunitare finantate in perioada 2021-2027</DEN_FOND_FINANTARE>
    <DEN_SURSA>Fonduri externe nerambursabile</DEN_SURSA>
    <ORDINE_AFISARE>278</ORDINE_AFISARE>
    <COD_INDICATOR>6608</COD_INDICATOR>
    <DEN_INDICATOR>SANATATE</DEN_INDICATOR>
    <CATEGORIE_RAND>II. Credite bugetare</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>2180</PROGRAM_2025>
    <ESTIMARI_2026>1260</ESTIMARI_2026>
    <ESTIMARI_2027>828</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>4268</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROIECTULUI FINANTAT/PROPUS LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 10/05</ANEXA>
    <COD_ORDONATOR>01</COD_ORDONATOR>
    <DEN_ORDONATOR>Casa Nationala de Asigurari de Sanatate</DEN_ORDONATOR>
    <CODFISCAL>11697800</CODFISCAL>
    <COD_PROGRAM_OPERATIONAL>109</COD_PROGRAM_OPERATIONAL>
    <DEN_PROGRAM_OPERATIONAL>Programul operational Sanatate 2021-2027</DEN_PROGRAM_OPERATIONAL>
    <COD_PROIECT>22238</COD_PROIECT>
    <DEN_PROIECT>Romanian ePrescription for Cross-Border e-Health &#40;ROEP&#41;</DEN_PROIECT>
    <COD_FOND_FINANTARE>64</COD_FOND_FINANTARE>
    <DEN_FOND_FINANTARE>Alte programe comunitare finantate in perioada 2021-2027</DEN_FOND_FINANTARE>
    <DEN_SURSA>Fonduri externe nerambursabile</DEN_SURSA>
    <ORDINE_AFISARE>279</ORDINE_AFISARE>
    <COD_INDICATOR>660856</COD_INDICATOR>
    <DEN_INDICATOR>TITLUL VIII PROIECTE CU FINANTARE DIN FONDURI EXTERNE NERAMBURSABILE &#40;FEN&#41; POSTADERARE</DEN_INDICATOR>
    <CATEGORIE_RAND>I.  Credite de angajament</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>