<?xml version="1.0" ?>
<!DOCTYPE main [
  <!ELEMENT main (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (TITLU_RAPORT,ANEXA?,COD_ORDONATOR?,DEN_ORDONATOR,CODFISCAL,COD_PROIECT,DEN_PROIECT,COD_INDICATOR,DEN_INDICATOR,CATEGORIE_RAND?,REALIZARI_PANA_IN_2022,REALIZARI_2023,EXECUTIE_PRELIMINATA_2024,PROGRAM_2025,ESTIMARI_2026,ESTIMARI_2027,ESTIMARI_2028,ANII_URMATORI,TOTAL)+>
  <!ELEMENT TITLU_RAPORT (#PCDATA)>
  <!ELEMENT ANEXA (#PCDATA)>
  <!ELEMENT COD_ORDONATOR (#PCDATA)>
  <!ELEMENT DEN_ORDONATOR (#PCDATA)>
  <!ELEMENT CODFISCAL (#PCDATA)>
  <!ELEMENT COD_PROIECT (#PCDATA)>
  <!ELEMENT DEN_PROIECT (#PCDATA)>
  <!ELEMENT COD_INDICATOR (#PCDATA)>
  <!ELEMENT DEN_INDICATOR (#PCDATA)>
  <!ELEMENT CATEGORIE_RAND (#PCDATA)>
  <!ELEMENT REALIZARI_PANA_IN_2022 (#PCDATA)>
  <!ELEMENT REALIZARI_2023 (#PCDATA)>
  <!ELEMENT EXECUTIE_PRELIMINATA_2024 (#PCDATA)>
  <!ELEMENT PROGRAM_2025 (#PCDATA)>
  <!ELEMENT ESTIMARI_2026 (#PCDATA)>
  <!ELEMENT ESTIMARI_2027 (#PCDATA)>
  <!ELEMENT ESTIMARI_2028 (#PCDATA)>
  <!ELEMENT ANII_URMATORI (#PCDATA)>
  <!ELEMENT TOTAL (#PCDATA)>
]>
<main>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA PROIECTELOR FINANTATE/PROPUSE LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT, PRECUM SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 3/04</ANEXA>
    <COD_ORDONATOR>21</COD_ORDONATOR>
    <DEN_ORDONATOR>Ministerul Muncii, Familiei, Tineretului si Solidaritatii Sociale</DEN_ORDONATOR>
    <CODFISCAL>11370190</CODFISCAL>
    <COD_PROIECT>0</COD_PROIECT>
    <DEN_PROIECT>TOTAL PROIECTE</DEN_PROIECT>
    <COD_INDICATOR>5000</COD_INDICATOR>
    <DEN_INDICATOR>TOTAL GENERAL</DEN_INDICATOR>
    <CATEGORIE_RAND>I.  Credite de angajament</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>1732</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>622100</PROGRAM_2025>
    <ESTIMARI_2026>1153476</ESTIMARI_2026>
    <ESTIMARI_2027>1200100</ESTIMARI_2027>
    <ESTIMARI_2028>1200100</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>4177508</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA PROIECTELOR FINANTATE/PROPUSE LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT, PRECUM SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 3/04</ANEXA>
    <COD_ORDONATOR>21</COD_ORDONATOR>
    <DEN_ORDONATOR>Ministerul Muncii, Familiei, Tineretului si Solidaritatii Sociale</DEN_ORDONATOR>
    <CODFISCAL>11370190</CODFISCAL>
    <COD_PROIECT>0</COD_PROIECT>
    <DEN_PROIECT>TOTAL PROIECTE</DEN_PROIECT>
    <COD_INDICATOR>5000</COD_INDICATOR>
    <DEN_INDICATOR>TOTAL GENERAL</DEN_INDICATOR>
    <CATEGORIE_RAND>II. Credite bugetare</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>1732</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>622100</PROGRAM_2025>
    <ESTIMARI_2026>1153476</ESTIMARI_2026>
    <ESTIMARI_2027>1200100</ESTIMARI_2027>
    <ESTIMARI_2028>1200100</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>4177508</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA PROIECTELOR FINANTATE/PROPUSE LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT, PRECUM SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 3/04</ANEXA>
    <COD_ORDONATOR>21</COD_ORDONATOR>
    <DEN_ORDONATOR>Ministerul Muncii, Familiei, Tineretului si Solidaritatii Sociale</DEN_ORDONATOR>
    <CODFISCAL>11370190</CODFISCAL>
    <COD_PROIECT>0</COD_PROIECT>
    <DEN_PROIECT>TOTAL PROIECTE</DEN_PROIECT>
    <COD_INDICATOR>65105649</COD_INDICATOR>
    <DEN_INDICATOR> Programe finantate din Fondul Social European Plus &#40;FSE+&#41;, aferente cadrului financiar 2021-2027</DEN_INDICATOR>
    <CATEGORIE_RAND>I.  Credite de angajament</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>10</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>100</PROGRAM_2025>
    <ESTIMARI_2026>100</ESTIMARI_2026>
    <ESTIMARI_2027>100</ESTIMARI_2027>
    <ESTIMARI_2028>100</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>410</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA PROIECTELOR FINANTATE/PROPUSE LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT, PRECUM SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 3/04</ANEXA>
    <COD_ORDONATOR>21</COD_ORDONATOR>
    <DEN_ORDONATOR>Ministerul Muncii, Familiei, Tineretului si Solidaritatii Sociale</DEN_ORDONATOR>
    <CODFISCAL>11370190</CODFISCAL>
    <COD_PROIECT>0</COD_PROIECT>
    <DEN_PROIECT>TOTAL PROIECTE</DEN_PROIECT>
    <COD_INDICATOR>65105649</COD_INDICATOR>
    <DEN_INDICATOR> Programe finantate din Fondul Social European Plus &#40;FSE+&#41;, aferente cadrului financiar 2021-2027</DEN_INDICATOR>
    <CATEGORIE_RAND>II. Credite bugetare</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>10</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>100</PROGRAM_2025>
    <ESTIMARI_2026>100</ESTIMARI_2026>
    <ESTIMARI_2027>100</ESTIMARI_2027>
    <ESTIMARI_2028>100</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>410</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA PROIECTELOR FINANTATE/PROPUSE LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT, PRECUM SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 3/04</ANEXA>
    <COD_ORDONATOR>21</COD_ORDONATOR>
    <DEN_ORDONATOR>Ministerul Muncii, Familiei, Tineretului si Solidaritatii Sociale</DEN_ORDONATOR>
    <CODFISCAL>11370190</CODFISCAL>
    <COD_PROIECT>0</COD_PROIECT>
    <DEN_PROIECT>TOTAL PROIECTE</DEN_PROIECT>
    <COD_INDICATOR>6510564901</COD_INDICATOR>
    <DEN_INDICATOR> Finantare nationala</DEN_INDICATOR>
    <CATEGORIE_RAND>I.  Credite de angajament</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>2</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>20</PROGRAM_2025>
    <ESTIMARI_2026>20</ESTIMARI_2026>
    <ESTIMARI_2027>20</ESTIMARI_2027>
    <ESTIMARI_2028>20</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>82</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA PROIECTELOR FINANTATE/PROPUSE LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT, PRECUM SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 3/04</ANEXA>
    <COD_ORDONATOR>21</COD_ORDONATOR>
    <DEN_ORDONATOR>Ministerul Muncii, Familiei, Tineretului si Solidaritatii Sociale</DEN_ORDONATOR>
    <CODFISCAL>11370190</CODFISCAL>
    <COD_PROIECT>0</COD_PROIECT>
    <DEN_PROIECT>TOTAL PROIECTE</DEN_PROIECT>
    <COD_INDICATOR>6510564901</COD_INDICATOR>
    <DEN_INDICATOR> Finantare nationala</DEN_INDICATOR>
    <CATEGORIE_RAND>II. Credite bugetare</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>2</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>20</PROGRAM_2025>
    <ESTIMARI_2026>20</ESTIMARI_2026>
    <ESTIMARI_2027>20</ESTIMARI_2027>
    <ESTIMARI_2028>20</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>82</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA PROIECTELOR FINANTATE/PROPUSE LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT, PRECUM SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 3/04</ANEXA>
    <COD_ORDONATOR>21</COD_ORDONATOR>
    <DEN_ORDONATOR>Ministerul Muncii, Familiei, Tineretului si Solidaritatii Sociale</DEN_ORDONATOR>
    <CODFISCAL>11370190</CODFISCAL>
    <COD_PROIECT>0</COD_PROIECT>
    <DEN_PROIECT>TOTAL PROIECTE</DEN_PROIECT>
    <COD_INDICATOR>6510564902</COD_INDICATOR>
    <DEN_INDICATOR> Finantare externa nerambursabila</DEN_INDICATOR>
    <CATEGORIE_RAND>I.  Credite de angajament</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>8</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>80</PROGRAM_2025>
    <ESTIMARI_2026>80</ESTIMARI_2026>
    <ESTIMARI_2027>80</ESTIMARI_2027>
    <ESTIMARI_2028>80</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>328</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA PROIECTELOR FINANTATE/PROPUSE LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT, PRECUM SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 3/04</ANEXA>
    <COD_ORDONATOR>21</COD_ORDONATOR>
    <DEN_ORDONATOR>Ministerul Muncii, Familiei, Tineretului si Solidaritatii Sociale</DEN_ORDONATOR>
    <CODFISCAL>11370190</CODFISCAL>
    <COD_PROIECT>0</COD_PROIECT>
    <DEN_PROIECT>TOTAL PROIECTE</DEN_PROIECT>
    <COD_INDICATOR>6510564902</COD_INDICATOR>
    <DEN_INDICATOR> Finantare externa nerambursabila</DEN_INDICATOR>
    <CATEGORIE_RAND>II. Credite bugetare</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>8</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>80</PROGRAM_2025>
    <ESTIMARI_2026>80</ESTIMARI_2026>
    <ESTIMARI_2027>80</ESTIMARI_2027>
    <ESTIMARI_2028>80</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>328</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA PROIECTELOR FINANTATE/PROPUSE LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT, PRECUM SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 3/04</ANEXA>
    <COD_ORDONATOR>21</COD_ORDONATOR>
    <DEN_ORDONATOR>Ministerul Muncii, Familiei, Tineretului si Solidaritatii Sociale</DEN_ORDONATOR>
    <CODFISCAL>11370190</CODFISCAL>
    <COD_PROIECT>0</COD_PROIECT>
    <DEN_PROIECT>TOTAL PROIECTE</DEN_PROIECT>
    <COD_INDICATOR>80045648</COD_INDICATOR>
    <DEN_INDICATOR> Programe finantate din Fondul European de Dezvoltare Regionala &#40;FEDR&#41;, aferente cadrului financiar 2021-2027</DEN_INDICATOR>
    <CATEGORIE_RAND>I.  Credite de angajament</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>241</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>358</PROGRAM_2025>
    <ESTIMARI_2026>50</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>649</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA PROIECTELOR FINANTATE/PROPUSE LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT, PRECUM SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 3/04</ANEXA>
    <COD_ORDONATOR>21</COD_ORDONATOR>
    <DEN_ORDONATOR>Ministerul Muncii, Familiei, Tineretului si Solidaritatii Sociale</DEN_ORDONATOR>
    <CODFISCAL>11370190</CODFISCAL>
    <COD_PROIECT>0</COD_PROIECT>
    <DEN_PROIECT>TOTAL PROIECTE</DEN_PROIECT>
    <COD_INDICATOR>80045648</COD_INDICATOR>
    <DEN_INDICATOR> Programe finantate din Fondul European de Dezvoltare Regionala &#40;FEDR&#41;, aferente cadrului financiar 2021-2027</DEN_INDICATOR>
    <CATEGORIE_RAND>II. Credite bugetare</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>241</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>358</PROGRAM_2025>
    <ESTIMARI_2026>50</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>649</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA PROIECTELOR FINANTATE/PROPUSE LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT, PRECUM SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 3/04</ANEXA>
    <COD_ORDONATOR>21</COD_ORDONATOR>
    <DEN_ORDONATOR>Ministerul Muncii, Familiei, Tineretului si Solidaritatii Sociale</DEN_ORDONATOR>
    <CODFISCAL>11370190</CODFISCAL>
    <COD_PROIECT>0</COD_PROIECT>
    <DEN_PROIECT>TOTAL PROIECTE</DEN_PROIECT>
    <COD_INDICATOR>8004564801</COD_INDICATOR>
    <DEN_INDICATOR> Finantare nationala</DEN_INDICATOR>
    <CATEGORIE_RAND>I.  Credite de angajament</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>48</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>71</PROGRAM_2025>
    <ESTIMARI_2026>10</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>129</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA PROIECTELOR FINANTATE/PROPUSE LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT, PRECUM SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 3/04</ANEXA>
    <COD_ORDONATOR>21</COD_ORDONATOR>
    <DEN_ORDONATOR>Ministerul Muncii, Familiei, Tineretului si Solidaritatii Sociale</DEN_ORDONATOR>
    <CODFISCAL>11370190</CODFISCAL>
    <COD_PROIECT>0</COD_PROIECT>
    <DEN_PROIECT>TOTAL PROIECTE</DEN_PROIECT>
    <COD_INDICATOR>8004564801</COD_INDICATOR>
    <DEN_INDICATOR> Finantare nationala</DEN_INDICATOR>
    <CATEGORIE_RAND>II. Credite bugetare</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>48</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>71</PROGRAM_2025>
    <ESTIMARI_2026>10</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>129</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA PROIECTELOR FINANTATE/PROPUSE LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT, PRECUM SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 3/04</ANEXA>
    <COD_ORDONATOR>21</COD_ORDONATOR>
    <DEN_ORDONATOR>Ministerul Muncii, Familiei, Tineretului si Solidaritatii Sociale</DEN_ORDONATOR>
    <CODFISCAL>11370190</CODFISCAL>
    <COD_PROIECT>0</COD_PROIECT>
    <DEN_PROIECT>TOTAL PROIECTE</DEN_PROIECT>
    <COD_INDICATOR>8004564802</COD_INDICATOR>
    <DEN_INDICATOR> Finantare externa nerambursabila</DEN_INDICATOR>
    <CATEGORIE_RAND>I.  Credite de angajament</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>193</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>287</PROGRAM_2025>
    <ESTIMARI_2026>40</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>520</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA PROIECTELOR FINANTATE/PROPUSE LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT, PRECUM SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 3/04</ANEXA>
    <COD_ORDONATOR>21</COD_ORDONATOR>
    <DEN_ORDONATOR>Ministerul Muncii, Familiei, Tineretului si Solidaritatii Sociale</DEN_ORDONATOR>
    <CODFISCAL>11370190</CODFISCAL>
    <COD_PROIECT>0</COD_PROIECT>
    <DEN_PROIECT>TOTAL PROIECTE</DEN_PROIECT>
    <COD_INDICATOR>8004564802</COD_INDICATOR>
    <DEN_INDICATOR> Finantare externa nerambursabila</DEN_INDICATOR>
    <CATEGORIE_RAND>II. Credite bugetare</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>193</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>287</PROGRAM_2025>
    <ESTIMARI_2026>40</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>520</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA PROIECTELOR FINANTATE/PROPUSE LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT, PRECUM SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 3/04</ANEXA>
    <COD_ORDONATOR>21</COD_ORDONATOR>
    <DEN_ORDONATOR>Ministerul Muncii, Familiei, Tineretului si Solidaritatii Sociale</DEN_ORDONATOR>
    <CODFISCAL>11370190</CODFISCAL>
    <COD_PROIECT>0</COD_PROIECT>
    <DEN_PROIECT>TOTAL PROIECTE</DEN_PROIECT>
    <COD_INDICATOR>80045649</COD_INDICATOR>
    <DEN_INDICATOR> Programe finantate din Fondul Social European Plus &#40;FSE+&#41;, aferente cadrului financiar 2021-2027</DEN_INDICATOR>
    <CATEGORIE_RAND>I.  Credite de angajament</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>1481</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>621642</PROGRAM_2025>
    <ESTIMARI_2026>1153326</ESTIMARI_2026>
    <ESTIMARI_2027>1200000</ESTIMARI_2027>
    <ESTIMARI_2028>1200000</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>4176449</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA PROIECTELOR FINANTATE/PROPUSE LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT, PRECUM SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 3/04</ANEXA>
    <COD_ORDONATOR>21</COD_ORDONATOR>
    <DEN_ORDONATOR>Ministerul Muncii, Familiei, Tineretului si Solidaritatii Sociale</DEN_ORDONATOR>
    <CODFISCAL>11370190</CODFISCAL>
    <COD_PROIECT>0</COD_PROIECT>
    <DEN_PROIECT>TOTAL PROIECTE</DEN_PROIECT>
    <COD_INDICATOR>80045649</COD_INDICATOR>
    <DEN_INDICATOR> Programe finantate din Fondul Social European Plus &#40;FSE+&#41;, aferente cadrului financiar 2021-2027</DEN_INDICATOR>
    <CATEGORIE_RAND>II. Credite bugetare</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>1481</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>621642</PROGRAM_2025>
    <ESTIMARI_2026>1153326</ESTIMARI_2026>
    <ESTIMARI_2027>1200000</ESTIMARI_2027>
    <ESTIMARI_2028>1200000</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>4176449</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA PROIECTELOR FINANTATE/PROPUSE LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT, PRECUM SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 3/04</ANEXA>
    <COD_ORDONATOR>21</COD_ORDONATOR>
    <DEN_ORDONATOR>Ministerul Muncii, Familiei, Tineretului si Solidaritatii Sociale</DEN_ORDONATOR>
    <CODFISCAL>11370190</CODFISCAL>
    <COD_PROIECT>0</COD_PROIECT>
    <DEN_PROIECT>TOTAL PROIECTE</DEN_PROIECT>
    <COD_INDICATOR>8004564901</COD_INDICATOR>
    <DEN_INDICATOR> Finantare nationala</DEN_INDICATOR>
    <CATEGORIE_RAND>I.  Credite de angajament</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>337</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>136658</PROGRAM_2025>
    <ESTIMARI_2026>217856</ESTIMARI_2026>
    <ESTIMARI_2027>264418</ESTIMARI_2027>
    <ESTIMARI_2028>267658</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>886927</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA PROIECTELOR FINANTATE/PROPUSE LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT, PRECUM SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 3/04</ANEXA>
    <COD_ORDONATOR>21</COD_ORDONATOR>
    <DEN_ORDONATOR>Ministerul Muncii, Familiei, Tineretului si Solidaritatii Sociale</DEN_ORDONATOR>
    <CODFISCAL>11370190</CODFISCAL>
    <COD_PROIECT>0</COD_PROIECT>
    <DEN_PROIECT>TOTAL PROIECTE</DEN_PROIECT>
    <COD_INDICATOR>8004564901</COD_INDICATOR>
    <DEN_INDICATOR> Finantare nationala</DEN_INDICATOR>
    <CATEGORIE_RAND>II. Credite bugetare</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>337</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>136658</PROGRAM_2025>
    <ESTIMARI_2026>217856</ESTIMARI_2026>
    <ESTIMARI_2027>264418</ESTIMARI_2027>
    <ESTIMARI_2028>267658</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>886927</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA PROIECTELOR FINANTATE/PROPUSE LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT, PRECUM SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 3/04</ANEXA>
    <COD_ORDONATOR>21</COD_ORDONATOR>
    <DEN_ORDONATOR>Ministerul Muncii, Familiei, Tineretului si Solidaritatii Sociale</DEN_ORDONATOR>
    <CODFISCAL>11370190</CODFISCAL>
    <COD_PROIECT>0</COD_PROIECT>
    <DEN_PROIECT>TOTAL PROIECTE</DEN_PROIECT>
    <COD_INDICATOR>8004564902</COD_INDICATOR>
    <DEN_INDICATOR> Finantare externa nerambursabila</DEN_INDICATOR>
    <CATEGORIE_RAND>I.  Credite de angajament</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>1144</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>484984</PROGRAM_2025>
    <ESTIMARI_2026>935470</ESTIMARI_2026>
    <ESTIMARI_2027>935582</ESTIMARI_2027>
    <ESTIMARI_2028>932342</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>3289522</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA PROIECTELOR FINANTATE/PROPUSE LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT, PRECUM SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 3/04</ANEXA>
    <COD_ORDONATOR>21</COD_ORDONATOR>
    <DEN_ORDONATOR>Ministerul Muncii, Familiei, Tineretului si Solidaritatii Sociale</DEN_ORDONATOR>
    <CODFISCAL>11370190</CODFISCAL>
    <COD_PROIECT>0</COD_PROIECT>
    <DEN_PROIECT>TOTAL PROIECTE</DEN_PROIECT>
    <COD_INDICATOR>8004564902</COD_INDICATOR>
    <DEN_INDICATOR> Finantare externa nerambursabila</DEN_INDICATOR>
    <CATEGORIE_RAND>II. Credite bugetare</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>1144</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>484984</PROGRAM_2025>
    <ESTIMARI_2026>935470</ESTIMARI_2026>
    <ESTIMARI_2027>935582</ESTIMARI_2027>
    <ESTIMARI_2028>932342</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>3289522</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA PROIECTELOR FINANTATE/PROPUSE LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT, PRECUM SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 3/04</ANEXA>
    <COD_ORDONATOR>21</COD_ORDONATOR>
    <DEN_ORDONATOR>Ministerul Muncii, Familiei, Tineretului si Solidaritatii Sociale</DEN_ORDONATOR>
    <CODFISCAL>11370190</CODFISCAL>
    <COD_PROIECT>23830</COD_PROIECT>
    <DEN_PROIECT>SMART SPO - Servicii moderne, accesibile si pregatite pentru viitor</DEN_PROIECT>
    <COD_INDICATOR>80045649</COD_INDICATOR>
    <DEN_INDICATOR> Programe finantate din Fondul Social European Plus &#40;FSE+&#41;, aferente cadrului financiar 2021-2027</DEN_INDICATOR>
    <CATEGORIE_RAND>I.  Credite de angajament</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>489605</PROGRAM_2025>
    <ESTIMARI_2026>997937</ESTIMARI_2026>
    <ESTIMARI_2027>1085480</ESTIMARI_2027>
    <ESTIMARI_2028>1121254</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>3694276</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA PROIECTELOR FINANTATE/PROPUSE LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT, PRECUM SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 3/04</ANEXA>
    <COD_ORDONATOR>21</COD_ORDONATOR>
    <DEN_ORDONATOR>Ministerul Muncii, Familiei, Tineretului si Solidaritatii Sociale</DEN_ORDONATOR>
    <CODFISCAL>11370190</CODFISCAL>
    <COD_PROIECT>23830</COD_PROIECT>
    <DEN_PROIECT>SMART SPO - Servicii moderne, accesibile si pregatite pentru viitor</DEN_PROIECT>
    <COD_INDICATOR>80045649</COD_INDICATOR>
    <DEN_INDICATOR> Programe finantate din Fondul Social European Plus &#40;FSE+&#41;, aferente cadrului financiar 2021-2027</DEN_INDICATOR>
    <CATEGORIE_RAND>II. Credite bugetare</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>489605</PROGRAM_2025>
    <ESTIMARI_2026>997937</ESTIMARI_2026>
    <ESTIMARI_2027>1085480</ESTIMARI_2027>
    <ESTIMARI_2028>1121254</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>3694276</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA PROIECTELOR FINANTATE/PROPUSE LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT, PRECUM SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 3/04</ANEXA>
    <COD_ORDONATOR>21</COD_ORDONATOR>
    <DEN_ORDONATOR>Ministerul Muncii, Familiei, Tineretului si Solidaritatii Sociale</DEN_ORDONATOR>
    <CODFISCAL>11370190</CODFISCAL>
    <COD_PROIECT>25405</COD_PROIECT>
    <DEN_PROIECT>Angajatii au Multiple Posibilitati prin Formare Moderna - Cod MySMIS 313073</DEN_PROIECT>
    <COD_INDICATOR>80045649</COD_INDICATOR>
    <DEN_INDICATOR> Programe finantate din Fondul Social European Plus &#40;FSE+&#41;, aferente cadrului financiar 2021-2027</DEN_INDICATOR>
    <CATEGORIE_RAND>I.  Credite de angajament</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>263</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>773</PROGRAM_2025>
    <ESTIMARI_2026>759</ESTIMARI_2026>
    <ESTIMARI_2027>397</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>2192</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA PROIECTELOR FINANTATE/PROPUSE LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT, PRECUM SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 3/04</ANEXA>
    <COD_ORDONATOR>21</COD_ORDONATOR>
    <DEN_ORDONATOR>Ministerul Muncii, Familiei, Tineretului si Solidaritatii Sociale</DEN_ORDONATOR>
    <CODFISCAL>11370190</CODFISCAL>
    <COD_PROIECT>25405</COD_PROIECT>
    <DEN_PROIECT>Angajatii au Multiple Posibilitati prin Formare Moderna - Cod MySMIS 313073</DEN_PROIECT>
    <COD_INDICATOR>80045649</COD_INDICATOR>
    <DEN_INDICATOR> Programe finantate din Fondul Social European Plus &#40;FSE+&#41;, aferente cadrului financiar 2021-2027</DEN_INDICATOR>
    <CATEGORIE_RAND>II. Credite bugetare</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>263</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>773</PROGRAM_2025>
    <ESTIMARI_2026>759</ESTIMARI_2026>
    <ESTIMARI_2027>397</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>2192</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA PROIECTELOR FINANTATE/PROPUSE LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT, PRECUM SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 3/04</ANEXA>
    <COD_ORDONATOR>21</COD_ORDONATOR>
    <DEN_ORDONATOR>Ministerul Muncii, Familiei, Tineretului si Solidaritatii Sociale</DEN_ORDONATOR>
    <CODFISCAL>11370190</CODFISCAL>
    <COD_PROIECT>25406</COD_PROIECT>
    <DEN_PROIECT>EURES - Targeted Mobility Scheme &#40;TMS&#41; Sweden 2 - 101127255</DEN_PROIECT>
    <COD_INDICATOR>80045649</COD_INDICATOR>
    <DEN_INDICATOR> Programe finantate din Fondul Social European Plus &#40;FSE+&#41;, aferente cadrului financiar 2021-2027</DEN_INDICATOR>
    <CATEGORIE_RAND>I.  Credite de angajament</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>21</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>53</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>74</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>