<?xml version="1.0" ?>
<!DOCTYPE main [
  <!ELEMENT main (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (TITLU_RAPORT,ANEXA?,NRCRT?,COD_ORDONATOR?,CODFISCAL?,DEN_ORDONATOR?,COD_PROIECT?,COD_INDICATOR?,DENUMIRE?,CHELT_EFECT_PANA_31_12_2023?,EXECUTIE_PRELIMINATA_2024?,PROGRAM_2025?,ESTIMARI_2026?,ESTIMARI_2027?,ESTIMARI_2028?,ESTIMARI_ANII_ULTERIORI?,TOTAL?)+>
  <!ELEMENT TITLU_RAPORT (#PCDATA)>
  <!ELEMENT ANEXA (#PCDATA)>
  <!ELEMENT NRCRT (#PCDATA)>
  <!ELEMENT COD_ORDONATOR (#PCDATA)>
  <!ELEMENT CODFISCAL (#PCDATA)>
  <!ELEMENT DEN_ORDONATOR (#PCDATA)>
  <!ELEMENT COD_PROIECT (#PCDATA)>
  <!ELEMENT COD_INDICATOR (#PCDATA)>
  <!ELEMENT DENUMIRE (#PCDATA)>
  <!ELEMENT CHELT_EFECT_PANA_31_12_2023 (#PCDATA)>
  <!ELEMENT EXECUTIE_PRELIMINATA_2024 (#PCDATA)>
  <!ELEMENT PROGRAM_2025 (#PCDATA)>
  <!ELEMENT ESTIMARI_2026 (#PCDATA)>
  <!ELEMENT ESTIMARI_2027 (#PCDATA)>
  <!ELEMENT ESTIMARI_2028 (#PCDATA)>
  <!ELEMENT ESTIMARI_ANII_ULTERIORI (#PCDATA)>
  <!ELEMENT TOTAL (#PCDATA)>
]>
<main>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA FINANTARII PROGRAMELOR POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.04</ANEXA>
    <NRCRT>2</NRCRT>
    <COD_ORDONATOR>13</COD_ORDONATOR>
    <CODFISCAL>4283422</CODFISCAL>
    <DEN_ORDONATOR>Secretariatul General al Guvernului</DEN_ORDONATOR>
    <COD_PROIECT>0</COD_PROIECT>
    <COD_INDICATOR>5000</COD_INDICATOR>
    <DENUMIRE>TOTAL CHELTUIELI</DENUMIRE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA FINANTARII PROGRAMELOR POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.04</ANEXA>
    <NRCRT>3</NRCRT>
    <COD_ORDONATOR>13</COD_ORDONATOR>
    <CODFISCAL>4283422</CODFISCAL>
    <DEN_ORDONATOR>Secretariatul General al Guvernului</DEN_ORDONATOR>
    <COD_PROIECT>0</COD_PROIECT>
    <COD_INDICATOR>5000</COD_INDICATOR>
    <DENUMIRE>I. Credite de angajament </DENUMIRE>
    <CHELT_EFECT_PANA_31_12_2023>41764</CHELT_EFECT_PANA_31_12_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>0</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ESTIMARI_ANII_ULTERIORI>0</ESTIMARI_ANII_ULTERIORI>
    <TOTAL>41764</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA FINANTARII PROGRAMELOR POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.04</ANEXA>
    <NRCRT>4</NRCRT>
    <COD_ORDONATOR>13</COD_ORDONATOR>
    <CODFISCAL>4283422</CODFISCAL>
    <DEN_ORDONATOR>Secretariatul General al Guvernului</DEN_ORDONATOR>
    <COD_PROIECT>0</COD_PROIECT>
    <COD_INDICATOR>5000</COD_INDICATOR>
    <DENUMIRE>II. Credite bugetare </DENUMIRE>
    <CHELT_EFECT_PANA_31_12_2023>41764</CHELT_EFECT_PANA_31_12_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>0</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ESTIMARI_ANII_ULTERIORI>0</ESTIMARI_ANII_ULTERIORI>
    <TOTAL>41764</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA FINANTARII PROGRAMELOR POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.04</ANEXA>
    <NRCRT>5</NRCRT>
    <COD_ORDONATOR>13</COD_ORDONATOR>
    <CODFISCAL>4283422</CODFISCAL>
    <DEN_ORDONATOR>Secretariatul General al Guvernului</DEN_ORDONATOR>
    <COD_PROIECT>72</COD_PROIECT>
    <DENUMIRE>Proiectul Completarea sprijinului financiar acordat de UE pentru restructurarea agriculturii</DENUMIRE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA FINANTARII PROGRAMELOR POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.04</ANEXA>
    <NRCRT>6</NRCRT>
    <COD_ORDONATOR>13</COD_ORDONATOR>
    <CODFISCAL>4283422</CODFISCAL>
    <DEN_ORDONATOR>Secretariatul General al Guvernului</DEN_ORDONATOR>
    <COD_PROIECT>72</COD_PROIECT>
    <COD_INDICATOR>5000</COD_INDICATOR>
    <DENUMIRE>TOTAL GENERAL</DENUMIRE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA FINANTARII PROGRAMELOR POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.04</ANEXA>
    <NRCRT>7</NRCRT>
    <COD_ORDONATOR>13</COD_ORDONATOR>
    <CODFISCAL>4283422</CODFISCAL>
    <DEN_ORDONATOR>Secretariatul General al Guvernului</DEN_ORDONATOR>
    <COD_PROIECT>72</COD_PROIECT>
    <COD_INDICATOR>5000</COD_INDICATOR>
    <DENUMIRE>I. Credite de angajament </DENUMIRE>
    <CHELT_EFECT_PANA_31_12_2023>41764</CHELT_EFECT_PANA_31_12_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>0</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ESTIMARI_ANII_ULTERIORI>0</ESTIMARI_ANII_ULTERIORI>
    <TOTAL>41764</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA FINANTARII PROGRAMELOR POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.04</ANEXA>
    <NRCRT>8</NRCRT>
    <COD_ORDONATOR>13</COD_ORDONATOR>
    <CODFISCAL>4283422</CODFISCAL>
    <DEN_ORDONATOR>Secretariatul General al Guvernului</DEN_ORDONATOR>
    <COD_PROIECT>72</COD_PROIECT>
    <COD_INDICATOR>5000</COD_INDICATOR>
    <DENUMIRE>II. Credite bugetare </DENUMIRE>
    <CHELT_EFECT_PANA_31_12_2023>41764</CHELT_EFECT_PANA_31_12_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>0</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ESTIMARI_ANII_ULTERIORI>0</ESTIMARI_ANII_ULTERIORI>
    <TOTAL>41764</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA FINANTARII PROGRAMELOR POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.04</ANEXA>
    <NRCRT>2</NRCRT>
    <COD_ORDONATOR>15</COD_ORDONATOR>
    <CODFISCAL>26369185</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Dezvoltarii, Lucrarilor Publice si Administratiei</DEN_ORDONATOR>
    <COD_PROIECT>0</COD_PROIECT>
    <COD_INDICATOR>5000</COD_INDICATOR>
    <DENUMIRE>TOTAL CHELTUIELI</DENUMIRE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA FINANTARII PROGRAMELOR POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.04</ANEXA>
    <NRCRT>3</NRCRT>
    <COD_ORDONATOR>15</COD_ORDONATOR>
    <CODFISCAL>26369185</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Dezvoltarii, Lucrarilor Publice si Administratiei</DEN_ORDONATOR>
    <COD_PROIECT>0</COD_PROIECT>
    <COD_INDICATOR>5000</COD_INDICATOR>
    <DENUMIRE>I. Credite de angajament </DENUMIRE>
    <CHELT_EFECT_PANA_31_12_2023>2363367</CHELT_EFECT_PANA_31_12_2023>
    <EXECUTIE_PRELIMINATA_2024>434343</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>530000</PROGRAM_2025>
    <ESTIMARI_2026>244278</ESTIMARI_2026>
    <ESTIMARI_2027>243147</ESTIMARI_2027>
    <ESTIMARI_2028>240990</ESTIMARI_2028>
    <ESTIMARI_ANII_ULTERIORI>0</ESTIMARI_ANII_ULTERIORI>
    <TOTAL>4056125</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA FINANTARII PROGRAMELOR POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.04</ANEXA>
    <NRCRT>4</NRCRT>
    <COD_ORDONATOR>15</COD_ORDONATOR>
    <CODFISCAL>26369185</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Dezvoltarii, Lucrarilor Publice si Administratiei</DEN_ORDONATOR>
    <COD_PROIECT>0</COD_PROIECT>
    <COD_INDICATOR>5000</COD_INDICATOR>
    <DENUMIRE>II. Credite bugetare </DENUMIRE>
    <CHELT_EFECT_PANA_31_12_2023>1027242</CHELT_EFECT_PANA_31_12_2023>
    <EXECUTIE_PRELIMINATA_2024>275000</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>282000</PROGRAM_2025>
    <ESTIMARI_2026>187278</ESTIMARI_2026>
    <ESTIMARI_2027>192147</ESTIMARI_2027>
    <ESTIMARI_2028>195990</ESTIMARI_2028>
    <ESTIMARI_ANII_ULTERIORI>1896468</ESTIMARI_ANII_ULTERIORI>
    <TOTAL>4056125</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA FINANTARII PROGRAMELOR POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.04</ANEXA>
    <NRCRT>5</NRCRT>
    <COD_ORDONATOR>15</COD_ORDONATOR>
    <CODFISCAL>26369185</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Dezvoltarii, Lucrarilor Publice si Administratiei</DEN_ORDONATOR>
    <COD_PROIECT>49</COD_PROIECT>
    <DENUMIRE>Proiectul privind constructia si reabilitarea de locuinte sociale pentru tineri destinate inchirierii</DENUMIRE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA FINANTARII PROGRAMELOR POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.04</ANEXA>
    <NRCRT>6</NRCRT>
    <COD_ORDONATOR>15</COD_ORDONATOR>
    <CODFISCAL>26369185</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Dezvoltarii, Lucrarilor Publice si Administratiei</DEN_ORDONATOR>
    <COD_PROIECT>49</COD_PROIECT>
    <COD_INDICATOR>5000</COD_INDICATOR>
    <DENUMIRE>TOTAL GENERAL</DENUMIRE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA FINANTARII PROGRAMELOR POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.04</ANEXA>
    <NRCRT>7</NRCRT>
    <COD_ORDONATOR>15</COD_ORDONATOR>
    <CODFISCAL>26369185</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Dezvoltarii, Lucrarilor Publice si Administratiei</DEN_ORDONATOR>
    <COD_PROIECT>49</COD_PROIECT>
    <COD_INDICATOR>5000</COD_INDICATOR>
    <DENUMIRE>I. Credite de angajament </DENUMIRE>
    <CHELT_EFECT_PANA_31_12_2023>146069</CHELT_EFECT_PANA_31_12_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>0</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ESTIMARI_ANII_ULTERIORI>0</ESTIMARI_ANII_ULTERIORI>
    <TOTAL>146069</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA FINANTARII PROGRAMELOR POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.04</ANEXA>
    <NRCRT>8</NRCRT>
    <COD_ORDONATOR>15</COD_ORDONATOR>
    <CODFISCAL>26369185</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Dezvoltarii, Lucrarilor Publice si Administratiei</DEN_ORDONATOR>
    <COD_PROIECT>49</COD_PROIECT>
    <COD_INDICATOR>5000</COD_INDICATOR>
    <DENUMIRE>II. Credite bugetare </DENUMIRE>
    <CHELT_EFECT_PANA_31_12_2023>146069</CHELT_EFECT_PANA_31_12_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>0</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ESTIMARI_ANII_ULTERIORI>0</ESTIMARI_ANII_ULTERIORI>
    <TOTAL>146069</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA FINANTARII PROGRAMELOR POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.04</ANEXA>
    <NRCRT>9</NRCRT>
    <COD_ORDONATOR>15</COD_ORDONATOR>
    <CODFISCAL>26369185</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Dezvoltarii, Lucrarilor Publice si Administratiei</DEN_ORDONATOR>
    <COD_PROIECT>56</COD_PROIECT>
    <DENUMIRE>Proiectul pentru realizarea sistemului de alimentare cu apa si canalizare in localitatile sub 50.000 de locuitori</DENUMIRE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA FINANTARII PROGRAMELOR POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.04</ANEXA>
    <NRCRT>10</NRCRT>
    <COD_ORDONATOR>15</COD_ORDONATOR>
    <CODFISCAL>26369185</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Dezvoltarii, Lucrarilor Publice si Administratiei</DEN_ORDONATOR>
    <COD_PROIECT>56</COD_PROIECT>
    <COD_INDICATOR>5000</COD_INDICATOR>
    <DENUMIRE>TOTAL GENERAL</DENUMIRE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA FINANTARII PROGRAMELOR POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.04</ANEXA>
    <NRCRT>11</NRCRT>
    <COD_ORDONATOR>15</COD_ORDONATOR>
    <CODFISCAL>26369185</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Dezvoltarii, Lucrarilor Publice si Administratiei</DEN_ORDONATOR>
    <COD_PROIECT>56</COD_PROIECT>
    <COD_INDICATOR>5000</COD_INDICATOR>
    <DENUMIRE>I. Credite de angajament </DENUMIRE>
    <CHELT_EFECT_PANA_31_12_2023>613123</CHELT_EFECT_PANA_31_12_2023>
    <EXECUTIE_PRELIMINATA_2024>2895</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>30000</PROGRAM_2025>
    <ESTIMARI_2026>5000</ESTIMARI_2026>
    <ESTIMARI_2027>5000</ESTIMARI_2027>
    <ESTIMARI_2028>1000</ESTIMARI_2028>
    <ESTIMARI_ANII_ULTERIORI>0</ESTIMARI_ANII_ULTERIORI>
    <TOTAL>657018</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA FINANTARII PROGRAMELOR POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.04</ANEXA>
    <NRCRT>12</NRCRT>
    <COD_ORDONATOR>15</COD_ORDONATOR>
    <CODFISCAL>26369185</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Dezvoltarii, Lucrarilor Publice si Administratiei</DEN_ORDONATOR>
    <COD_PROIECT>56</COD_PROIECT>
    <COD_INDICATOR>5000</COD_INDICATOR>
    <DENUMIRE>II. Credite bugetare </DENUMIRE>
    <CHELT_EFECT_PANA_31_12_2023>613123</CHELT_EFECT_PANA_31_12_2023>
    <EXECUTIE_PRELIMINATA_2024>2500</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>2000</PROGRAM_2025>
    <ESTIMARI_2026>5000</ESTIMARI_2026>
    <ESTIMARI_2027>5000</ESTIMARI_2027>
    <ESTIMARI_2028>1000</ESTIMARI_2028>
    <ESTIMARI_ANII_ULTERIORI>28395</ESTIMARI_ANII_ULTERIORI>
    <TOTAL>657018</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA FINANTARII PROGRAMELOR POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.04</ANEXA>
    <NRCRT>13</NRCRT>
    <COD_ORDONATOR>15</COD_ORDONATOR>
    <CODFISCAL>26369185</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Dezvoltarii, Lucrarilor Publice si Administratiei</DEN_ORDONATOR>
    <COD_PROIECT>10875</COD_PROIECT>
    <DENUMIRE>Proiectul privind constructia de locuinte pentru persoanele/familiile tinere din Romania, destinate inchirierii</DENUMIRE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA FINANTARII PROGRAMELOR POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.04</ANEXA>
    <NRCRT>14</NRCRT>
    <COD_ORDONATOR>15</COD_ORDONATOR>
    <CODFISCAL>26369185</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Dezvoltarii, Lucrarilor Publice si Administratiei</DEN_ORDONATOR>
    <COD_PROIECT>10875</COD_PROIECT>
    <COD_INDICATOR>5000</COD_INDICATOR>
    <DENUMIRE>TOTAL GENERAL</DENUMIRE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA FINANTARII PROGRAMELOR POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.04</ANEXA>
    <NRCRT>15</NRCRT>
    <COD_ORDONATOR>15</COD_ORDONATOR>
    <CODFISCAL>26369185</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Dezvoltarii, Lucrarilor Publice si Administratiei</DEN_ORDONATOR>
    <COD_PROIECT>10875</COD_PROIECT>
    <COD_INDICATOR>5000</COD_INDICATOR>
    <DENUMIRE>I. Credite de angajament </DENUMIRE>
    <CHELT_EFECT_PANA_31_12_2023>1428675</CHELT_EFECT_PANA_31_12_2023>
    <EXECUTIE_PRELIMINATA_2024>83358</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>130000</PROGRAM_2025>
    <ESTIMARI_2026>100000</ESTIMARI_2026>
    <ESTIMARI_2027>100000</ESTIMARI_2027>
    <ESTIMARI_2028>100000</ESTIMARI_2028>
    <ESTIMARI_ANII_ULTERIORI>0</ESTIMARI_ANII_ULTERIORI>
    <TOTAL>1942033</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA FINANTARII PROGRAMELOR POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.04</ANEXA>
    <NRCRT>16</NRCRT>
    <COD_ORDONATOR>15</COD_ORDONATOR>
    <CODFISCAL>26369185</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Dezvoltarii, Lucrarilor Publice si Administratiei</DEN_ORDONATOR>
    <COD_PROIECT>10875</COD_PROIECT>
    <COD_INDICATOR>5000</COD_INDICATOR>
    <DENUMIRE>II. Credite bugetare </DENUMIRE>
    <CHELT_EFECT_PANA_31_12_2023>259050</CHELT_EFECT_PANA_31_12_2023>
    <EXECUTIE_PRELIMINATA_2024>70682</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>50000</PROGRAM_2025>
    <ESTIMARI_2026>73000</ESTIMARI_2026>
    <ESTIMARI_2027>74000</ESTIMARI_2027>
    <ESTIMARI_2028>75000</ESTIMARI_2028>
    <ESTIMARI_ANII_ULTERIORI>1340301</ESTIMARI_ANII_ULTERIORI>
    <TOTAL>1942033</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA FINANTARII PROGRAMELOR POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.04</ANEXA>
    <NRCRT>17</NRCRT>
    <COD_ORDONATOR>15</COD_ORDONATOR>
    <CODFISCAL>26369185</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Dezvoltarii, Lucrarilor Publice si Administratiei</DEN_ORDONATOR>
    <COD_PROIECT>20745</COD_PROIECT>
    <DENUMIRE>PROGRAM CONSTRUCTII LOCUINTE DE SERVICIU</DENUMIRE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA FINANTARII PROGRAMELOR POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.04</ANEXA>
    <NRCRT>18</NRCRT>
    <COD_ORDONATOR>15</COD_ORDONATOR>
    <CODFISCAL>26369185</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Dezvoltarii, Lucrarilor Publice si Administratiei</DEN_ORDONATOR>
    <COD_PROIECT>20745</COD_PROIECT>
    <COD_INDICATOR>5000</COD_INDICATOR>
    <DENUMIRE>TOTAL GENERAL</DENUMIRE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA FINANTARII PROGRAMELOR POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.04</ANEXA>
    <NRCRT>19</NRCRT>
    <COD_ORDONATOR>15</COD_ORDONATOR>
    <CODFISCAL>26369185</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Dezvoltarii, Lucrarilor Publice si Administratiei</DEN_ORDONATOR>
    <COD_PROIECT>20745</COD_PROIECT>
    <COD_INDICATOR>5000</COD_INDICATOR>
    <DENUMIRE>I. Credite de angajament </DENUMIRE>
    <CHELT_EFECT_PANA_31_12_2023>175500</CHELT_EFECT_PANA_31_12_2023>
    <EXECUTIE_PRELIMINATA_2024>1500</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>20000</PROGRAM_2025>
    <ESTIMARI_2026>50000</ESTIMARI_2026>
    <ESTIMARI_2027>50000</ESTIMARI_2027>
    <ESTIMARI_2028>50000</ESTIMARI_2028>
    <ESTIMARI_ANII_ULTERIORI>0</ESTIMARI_ANII_ULTERIORI>
    <TOTAL>347000</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA FINANTARII PROGRAMELOR POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.04</ANEXA>
    <NRCRT>20</NRCRT>
    <COD_ORDONATOR>15</COD_ORDONATOR>
    <CODFISCAL>26369185</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Dezvoltarii, Lucrarilor Publice si Administratiei</DEN_ORDONATOR>
    <COD_PROIECT>20745</COD_PROIECT>
    <COD_INDICATOR>5000</COD_INDICATOR>
    <DENUMIRE>II. Credite bugetare </DENUMIRE>
    <CHELT_EFECT_PANA_31_12_2023>9000</CHELT_EFECT_PANA_31_12_2023>
    <EXECUTIE_PRELIMINATA_2024>1818</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>1500</PROGRAM_2025>
    <ESTIMARI_2026>20000</ESTIMARI_2026>
    <ESTIMARI_2027>25000</ESTIMARI_2027>
    <ESTIMARI_2028>30000</ESTIMARI_2028>
    <ESTIMARI_ANII_ULTERIORI>259682</ESTIMARI_ANII_ULTERIORI>
    <TOTAL>347000</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA FINANTARII PROGRAMELOR POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.04</ANEXA>
    <NRCRT>21</NRCRT>
    <COD_ORDONATOR>15</COD_ORDONATOR>
    <CODFISCAL>26369185</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Dezvoltarii, Lucrarilor Publice si Administratiei</DEN_ORDONATOR>
    <COD_PROIECT>23965</COD_PROIECT>
    <DENUMIRE>Raspunsul sectorului public din Romania la Covid 19 - Proiect I</DENUMIRE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA FINANTARII PROGRAMELOR POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.04</ANEXA>
    <NRCRT>22</NRCRT>
    <COD_ORDONATOR>15</COD_ORDONATOR>
    <CODFISCAL>26369185</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Dezvoltarii, Lucrarilor Publice si Administratiei</DEN_ORDONATOR>
    <COD_PROIECT>23965</COD_PROIECT>
    <COD_INDICATOR>5000</COD_INDICATOR>
    <DENUMIRE>TOTAL GENERAL</DENUMIRE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA FINANTARII PROGRAMELOR POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.04</ANEXA>
    <NRCRT>23</NRCRT>
    <COD_ORDONATOR>15</COD_ORDONATOR>
    <CODFISCAL>26369185</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Dezvoltarii, Lucrarilor Publice si Administratiei</DEN_ORDONATOR>
    <COD_PROIECT>23965</COD_PROIECT>
    <COD_INDICATOR>5000</COD_INDICATOR>
    <DENUMIRE>I. Credite de angajament </DENUMIRE>
    <CHELT_EFECT_PANA_31_12_2023>0</CHELT_EFECT_PANA_31_12_2023>
    <EXECUTIE_PRELIMINATA_2024>115827</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>205293</PROGRAM_2025>
    <ESTIMARI_2026>40000</ESTIMARI_2026>
    <ESTIMARI_2027>41000</ESTIMARI_2027>
    <ESTIMARI_2028>42000</ESTIMARI_2028>
    <ESTIMARI_ANII_ULTERIORI>0</ESTIMARI_ANII_ULTERIORI>
    <TOTAL>444120</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA FINANTARII PROGRAMELOR POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.04</ANEXA>
    <NRCRT>24</NRCRT>
    <COD_ORDONATOR>15</COD_ORDONATOR>
    <CODFISCAL>26369185</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Dezvoltarii, Lucrarilor Publice si Administratiei</DEN_ORDONATOR>
    <COD_PROIECT>23965</COD_PROIECT>
    <COD_INDICATOR>5000</COD_INDICATOR>
    <DENUMIRE>II. Credite bugetare </DENUMIRE>
    <CHELT_EFECT_PANA_31_12_2023>0</CHELT_EFECT_PANA_31_12_2023>
    <EXECUTIE_PRELIMINATA_2024>93500</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>138500</PROGRAM_2025>
    <ESTIMARI_2026>40000</ESTIMARI_2026>
    <ESTIMARI_2027>41000</ESTIMARI_2027>
    <ESTIMARI_2028>42000</ESTIMARI_2028>
    <ESTIMARI_ANII_ULTERIORI>89120</ESTIMARI_ANII_ULTERIORI>
    <TOTAL>444120</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA FINANTARII PROGRAMELOR POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.04</ANEXA>
    <NRCRT>25</NRCRT>
    <COD_ORDONATOR>15</COD_ORDONATOR>
    <CODFISCAL>26369185</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Dezvoltarii, Lucrarilor Publice si Administratiei</DEN_ORDONATOR>
    <COD_PROIECT>23966</COD_PROIECT>
    <DENUMIRE>&#9;Raspunsul sectorului public din Romania la Covid 19 - Proiect II</DENUMIRE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA FINANTARII PROGRAMELOR POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.04</ANEXA>
    <NRCRT>26</NRCRT>
    <COD_ORDONATOR>15</COD_ORDONATOR>
    <CODFISCAL>26369185</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Dezvoltarii, Lucrarilor Publice si Administratiei</DEN_ORDONATOR>
    <COD_PROIECT>23966</COD_PROIECT>
    <COD_INDICATOR>5000</COD_INDICATOR>
    <DENUMIRE>TOTAL GENERAL</DENUMIRE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA FINANTARII PROGRAMELOR POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.04</ANEXA>
    <NRCRT>27</NRCRT>
    <COD_ORDONATOR>15</COD_ORDONATOR>
    <CODFISCAL>26369185</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Dezvoltarii, Lucrarilor Publice si Administratiei</DEN_ORDONATOR>
    <COD_PROIECT>23966</COD_PROIECT>
    <COD_INDICATOR>5000</COD_INDICATOR>
    <DENUMIRE>I. Credite de angajament </DENUMIRE>
    <CHELT_EFECT_PANA_31_12_2023>0</CHELT_EFECT_PANA_31_12_2023>
    <EXECUTIE_PRELIMINATA_2024>230763</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>144707</PROGRAM_2025>
    <ESTIMARI_2026>49278</ESTIMARI_2026>
    <ESTIMARI_2027>47147</ESTIMARI_2027>
    <ESTIMARI_2028>47990</ESTIMARI_2028>
    <ESTIMARI_ANII_ULTERIORI>0</ESTIMARI_ANII_ULTERIORI>
    <TOTAL>519885</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA FINANTARII PROGRAMELOR POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.04</ANEXA>
    <NRCRT>28</NRCRT>
    <COD_ORDONATOR>15</COD_ORDONATOR>
    <CODFISCAL>26369185</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Dezvoltarii, Lucrarilor Publice si Administratiei</DEN_ORDONATOR>
    <COD_PROIECT>23966</COD_PROIECT>
    <COD_INDICATOR>5000</COD_INDICATOR>
    <DENUMIRE>II. Credite bugetare </DENUMIRE>
    <CHELT_EFECT_PANA_31_12_2023>0</CHELT_EFECT_PANA_31_12_2023>
    <EXECUTIE_PRELIMINATA_2024>106500</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>90000</PROGRAM_2025>
    <ESTIMARI_2026>49278</ESTIMARI_2026>
    <ESTIMARI_2027>47147</ESTIMARI_2027>
    <ESTIMARI_2028>47990</ESTIMARI_2028>
    <ESTIMARI_ANII_ULTERIORI>178970</ESTIMARI_ANII_ULTERIORI>
    <TOTAL>519885</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA FINANTARII PROGRAMELOR POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.04</ANEXA>
    <NRCRT>2</NRCRT>
    <COD_ORDONATOR>16</COD_ORDONATOR>
    <CODFISCAL>4221306</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Finantelor</DEN_ORDONATOR>
    <COD_PROIECT>0</COD_PROIECT>
    <COD_INDICATOR>5000</COD_INDICATOR>
    <DENUMIRE>TOTAL CHELTUIELI</DENUMIRE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA FINANTARII PROGRAMELOR POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.04</ANEXA>
    <NRCRT>3</NRCRT>
    <COD_ORDONATOR>16</COD_ORDONATOR>
    <CODFISCAL>4221306</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Finantelor</DEN_ORDONATOR>
    <COD_PROIECT>0</COD_PROIECT>
    <COD_INDICATOR>5000</COD_INDICATOR>
    <DENUMIRE>I. Credite de angajament </DENUMIRE>
    <CHELT_EFECT_PANA_31_12_2023>149790</CHELT_EFECT_PANA_31_12_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>0</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ESTIMARI_ANII_ULTERIORI>0</ESTIMARI_ANII_ULTERIORI>
    <TOTAL>149790</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA FINANTARII PROGRAMELOR POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.04</ANEXA>
    <NRCRT>4</NRCRT>
    <COD_ORDONATOR>16</COD_ORDONATOR>
    <CODFISCAL>4221306</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Finantelor</DEN_ORDONATOR>
    <COD_PROIECT>0</COD_PROIECT>
    <COD_INDICATOR>5000</COD_INDICATOR>
    <DENUMIRE>II. Credite bugetare </DENUMIRE>
    <CHELT_EFECT_PANA_31_12_2023>149790</CHELT_EFECT_PANA_31_12_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>0</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ESTIMARI_ANII_ULTERIORI>0</ESTIMARI_ANII_ULTERIORI>
    <TOTAL>149790</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA FINANTARII PROGRAMELOR POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.04</ANEXA>
    <NRCRT>5</NRCRT>
    <COD_ORDONATOR>16</COD_ORDONATOR>
    <CODFISCAL>4221306</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Finantelor</DEN_ORDONATOR>
    <COD_PROIECT>51</COD_PROIECT>
    <DENUMIRE>Proiectul privind incluziunea sociala</DENUMIRE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA FINANTARII PROGRAMELOR POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.04</ANEXA>
    <NRCRT>6</NRCRT>
    <COD_ORDONATOR>16</COD_ORDONATOR>
    <CODFISCAL>4221306</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Finantelor</DEN_ORDONATOR>
    <COD_PROIECT>51</COD_PROIECT>
    <COD_INDICATOR>5000</COD_INDICATOR>
    <DENUMIRE>TOTAL GENERAL</DENUMIRE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA FINANTARII PROGRAMELOR POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.04</ANEXA>
    <NRCRT>7</NRCRT>
    <COD_ORDONATOR>16</COD_ORDONATOR>
    <CODFISCAL>4221306</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Finantelor</DEN_ORDONATOR>
    <COD_PROIECT>51</COD_PROIECT>
    <COD_INDICATOR>5000</COD_INDICATOR>
    <DENUMIRE>I. Credite de angajament </DENUMIRE>
    <CHELT_EFECT_PANA_31_12_2023>72053</CHELT_EFECT_PANA_31_12_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>0</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ESTIMARI_ANII_ULTERIORI>0</ESTIMARI_ANII_ULTERIORI>
    <TOTAL>72053</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA FINANTARII PROGRAMELOR POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.04</ANEXA>
    <NRCRT>8</NRCRT>
    <COD_ORDONATOR>16</COD_ORDONATOR>
    <CODFISCAL>4221306</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Finantelor</DEN_ORDONATOR>
    <COD_PROIECT>51</COD_PROIECT>
    <COD_INDICATOR>5000</COD_INDICATOR>
    <DENUMIRE>II. Credite bugetare </DENUMIRE>
    <CHELT_EFECT_PANA_31_12_2023>72053</CHELT_EFECT_PANA_31_12_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>0</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ESTIMARI_ANII_ULTERIORI>0</ESTIMARI_ANII_ULTERIORI>
    <TOTAL>72053</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA FINANTARII PROGRAMELOR POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.04</ANEXA>
    <NRCRT>9</NRCRT>
    <COD_ORDONATOR>16</COD_ORDONATOR>
    <CODFISCAL>4221306</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Finantelor</DEN_ORDONATOR>
    <COD_PROIECT>4091</COD_PROIECT>
    <DENUMIRE>Programul de modernizare a administratiei fiscale - Banca Mondiala</DENUMIRE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA FINANTARII PROGRAMELOR POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.04</ANEXA>
    <NRCRT>10</NRCRT>
    <COD_ORDONATOR>16</COD_ORDONATOR>
    <CODFISCAL>4221306</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Finantelor</DEN_ORDONATOR>