<?xml version="1.0" ?>
<!DOCTYPE main [
  <!ELEMENT main (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (TITLU_RAPORT,ANEXA?,NRCRT?,COD_ORDONATOR?,CODFISCAL?,DEN_ORDONATOR?,COD_PROIECT?,COD_INDICATOR?,DENUMIRE?,CHE_PANA_LA_31_12_2023?,EXECUTIE_PRELIMINATA_2024?,PROGRAM_2025?,ESTIMARI_2026?,ESTIMARI_2027?,ESTIMARI_2028?,ESTIMARI_ANII_ULTERIORI?,TOTAL?)+>
  <!ELEMENT TITLU_RAPORT (#PCDATA)>
  <!ELEMENT ANEXA (#PCDATA)>
  <!ELEMENT NRCRT (#PCDATA)>
  <!ELEMENT COD_ORDONATOR (#PCDATA)>
  <!ELEMENT CODFISCAL (#PCDATA)>
  <!ELEMENT DEN_ORDONATOR (#PCDATA)>
  <!ELEMENT COD_PROIECT (#PCDATA)>
  <!ELEMENT COD_INDICATOR (#PCDATA)>
  <!ELEMENT DENUMIRE (#PCDATA)>
  <!ELEMENT CHE_PANA_LA_31_12_2023 (#PCDATA)>
  <!ELEMENT EXECUTIE_PRELIMINATA_2024 (#PCDATA)>
  <!ELEMENT PROGRAM_2025 (#PCDATA)>
  <!ELEMENT ESTIMARI_2026 (#PCDATA)>
  <!ELEMENT ESTIMARI_2027 (#PCDATA)>
  <!ELEMENT ESTIMARI_2028 (#PCDATA)>
  <!ELEMENT ESTIMARI_ANII_ULTERIORI (#PCDATA)>
  <!ELEMENT TOTAL (#PCDATA)>
]>
<main>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROGRAMULUI FINANTAT POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.05</ANEXA>
    <NRCRT>2</NRCRT>
    <COD_ORDONATOR>13</COD_ORDONATOR>
    <CODFISCAL>4283422</CODFISCAL>
    <DEN_ORDONATOR>Secretariatul General al Guvernului</DEN_ORDONATOR>
    <COD_PROIECT>72</COD_PROIECT>
    <DENUMIRE>Proiectul Completarea sprijinului financiar acordat de UE pentru restructurarea agriculturii</DENUMIRE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROGRAMULUI FINANTAT POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.05</ANEXA>
    <NRCRT>3</NRCRT>
    <COD_ORDONATOR>13</COD_ORDONATOR>
    <CODFISCAL>4283422</CODFISCAL>
    <DEN_ORDONATOR>Secretariatul General al Guvernului</DEN_ORDONATOR>
    <COD_PROIECT>72</COD_PROIECT>
    <COD_INDICATOR>5000</COD_INDICATOR>
    <DENUMIRE>TOTAL GENERAL</DENUMIRE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROGRAMULUI FINANTAT POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.05</ANEXA>
    <NRCRT>4</NRCRT>
    <COD_ORDONATOR>13</COD_ORDONATOR>
    <CODFISCAL>4283422</CODFISCAL>
    <DEN_ORDONATOR>Secretariatul General al Guvernului</DEN_ORDONATOR>
    <COD_PROIECT>72</COD_PROIECT>
    <COD_INDICATOR>5000</COD_INDICATOR>
    <DENUMIRE>I. Credite de angajament </DENUMIRE>
    <CHE_PANA_LA_31_12_2023>41764</CHE_PANA_LA_31_12_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>0</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ESTIMARI_ANII_ULTERIORI>0</ESTIMARI_ANII_ULTERIORI>
    <TOTAL>41764</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROGRAMULUI FINANTAT POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.05</ANEXA>
    <NRCRT>5</NRCRT>
    <COD_ORDONATOR>13</COD_ORDONATOR>
    <CODFISCAL>4283422</CODFISCAL>
    <DEN_ORDONATOR>Secretariatul General al Guvernului</DEN_ORDONATOR>
    <COD_PROIECT>72</COD_PROIECT>
    <COD_INDICATOR>5000</COD_INDICATOR>
    <DENUMIRE>II. Credite bugetare </DENUMIRE>
    <CHE_PANA_LA_31_12_2023>41764</CHE_PANA_LA_31_12_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>0</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ESTIMARI_ANII_ULTERIORI>0</ESTIMARI_ANII_ULTERIORI>
    <TOTAL>41764</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROGRAMULUI FINANTAT POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.05</ANEXA>
    <NRCRT>6</NRCRT>
    <COD_ORDONATOR>13</COD_ORDONATOR>
    <CODFISCAL>4283422</CODFISCAL>
    <DEN_ORDONATOR>Secretariatul General al Guvernului</DEN_ORDONATOR>
    <COD_PROIECT>72</COD_PROIECT>
    <DENUMIRE>Buget de stat</DENUMIRE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROGRAMULUI FINANTAT POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.05</ANEXA>
    <NRCRT>7</NRCRT>
    <COD_ORDONATOR>13</COD_ORDONATOR>
    <CODFISCAL>4283422</CODFISCAL>
    <DEN_ORDONATOR>Secretariatul General al Guvernului</DEN_ORDONATOR>
    <COD_PROIECT>72</COD_PROIECT>
    <COD_INDICATOR>5001</COD_INDICATOR>
    <DENUMIRE>CHELTUIELI - BUGET DE STAT</DENUMIRE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROGRAMULUI FINANTAT POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.05</ANEXA>
    <NRCRT>8</NRCRT>
    <COD_ORDONATOR>13</COD_ORDONATOR>
    <CODFISCAL>4283422</CODFISCAL>
    <DEN_ORDONATOR>Secretariatul General al Guvernului</DEN_ORDONATOR>
    <COD_PROIECT>72</COD_PROIECT>
    <COD_INDICATOR>5001</COD_INDICATOR>
    <DENUMIRE>I. Credite de angajament </DENUMIRE>
    <CHE_PANA_LA_31_12_2023>41764</CHE_PANA_LA_31_12_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>0</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ESTIMARI_ANII_ULTERIORI>0</ESTIMARI_ANII_ULTERIORI>
    <TOTAL>41764</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROGRAMULUI FINANTAT POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.05</ANEXA>
    <NRCRT>9</NRCRT>
    <COD_ORDONATOR>13</COD_ORDONATOR>
    <CODFISCAL>4283422</CODFISCAL>
    <DEN_ORDONATOR>Secretariatul General al Guvernului</DEN_ORDONATOR>
    <COD_PROIECT>72</COD_PROIECT>
    <COD_INDICATOR>5001</COD_INDICATOR>
    <DENUMIRE>II. Credite bugetare </DENUMIRE>
    <CHE_PANA_LA_31_12_2023>41764</CHE_PANA_LA_31_12_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>0</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ESTIMARI_ANII_ULTERIORI>0</ESTIMARI_ANII_ULTERIORI>
    <TOTAL>41764</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROGRAMULUI FINANTAT POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.05</ANEXA>
    <NRCRT>10</NRCRT>
    <COD_ORDONATOR>13</COD_ORDONATOR>
    <CODFISCAL>4283422</CODFISCAL>
    <DEN_ORDONATOR>Secretariatul General al Guvernului</DEN_ORDONATOR>
    <COD_PROIECT>72</COD_PROIECT>
    <COD_INDICATOR>5101</COD_INDICATOR>
    <DENUMIRE>AUTORITATI PUBLICE SI ACTIUNI EXTERNE</DENUMIRE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROGRAMULUI FINANTAT POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.05</ANEXA>
    <NRCRT>11</NRCRT>
    <COD_ORDONATOR>13</COD_ORDONATOR>
    <CODFISCAL>4283422</CODFISCAL>
    <DEN_ORDONATOR>Secretariatul General al Guvernului</DEN_ORDONATOR>
    <COD_PROIECT>72</COD_PROIECT>
    <COD_INDICATOR>5101</COD_INDICATOR>
    <DENUMIRE>I. Credite de angajament </DENUMIRE>
    <CHE_PANA_LA_31_12_2023>41764</CHE_PANA_LA_31_12_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>0</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ESTIMARI_ANII_ULTERIORI>0</ESTIMARI_ANII_ULTERIORI>
    <TOTAL>41764</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROGRAMULUI FINANTAT POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.05</ANEXA>
    <NRCRT>12</NRCRT>
    <COD_ORDONATOR>13</COD_ORDONATOR>
    <CODFISCAL>4283422</CODFISCAL>
    <DEN_ORDONATOR>Secretariatul General al Guvernului</DEN_ORDONATOR>
    <COD_PROIECT>72</COD_PROIECT>
    <COD_INDICATOR>5101</COD_INDICATOR>
    <DENUMIRE>II. Credite bugetare </DENUMIRE>
    <CHE_PANA_LA_31_12_2023>41764</CHE_PANA_LA_31_12_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>0</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ESTIMARI_ANII_ULTERIORI>0</ESTIMARI_ANII_ULTERIORI>
    <TOTAL>41764</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROGRAMULUI FINANTAT POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.05</ANEXA>
    <NRCRT>13</NRCRT>
    <COD_ORDONATOR>13</COD_ORDONATOR>
    <CODFISCAL>4283422</CODFISCAL>
    <DEN_ORDONATOR>Secretariatul General al Guvernului</DEN_ORDONATOR>
    <COD_PROIECT>72</COD_PROIECT>
    <COD_INDICATOR>510165</COD_INDICATOR>
    <DENUMIRE>TITLUL XIV CHELTUIELI AFERENTE PROGRAMELOR CU FINANTARE RAMBURSABILA</DENUMIRE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROGRAMULUI FINANTAT POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.05</ANEXA>
    <NRCRT>14</NRCRT>
    <COD_ORDONATOR>13</COD_ORDONATOR>
    <CODFISCAL>4283422</CODFISCAL>
    <DEN_ORDONATOR>Secretariatul General al Guvernului</DEN_ORDONATOR>
    <COD_PROIECT>72</COD_PROIECT>
    <COD_INDICATOR>510165</COD_INDICATOR>
    <DENUMIRE>I. Credite de angajament </DENUMIRE>
    <CHE_PANA_LA_31_12_2023>41764</CHE_PANA_LA_31_12_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>0</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ESTIMARI_ANII_ULTERIORI>0</ESTIMARI_ANII_ULTERIORI>
    <TOTAL>41764</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROGRAMULUI FINANTAT POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.05</ANEXA>
    <NRCRT>15</NRCRT>
    <COD_ORDONATOR>13</COD_ORDONATOR>
    <CODFISCAL>4283422</CODFISCAL>
    <DEN_ORDONATOR>Secretariatul General al Guvernului</DEN_ORDONATOR>
    <COD_PROIECT>72</COD_PROIECT>
    <COD_INDICATOR>510165</COD_INDICATOR>
    <DENUMIRE>II. Credite bugetare </DENUMIRE>
    <CHE_PANA_LA_31_12_2023>41764</CHE_PANA_LA_31_12_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>0</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ESTIMARI_ANII_ULTERIORI>0</ESTIMARI_ANII_ULTERIORI>
    <TOTAL>41764</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROGRAMULUI FINANTAT POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.05</ANEXA>
    <NRCRT>2</NRCRT>
    <COD_ORDONATOR>15</COD_ORDONATOR>
    <CODFISCAL>26369185</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Dezvoltarii, Lucrarilor Publice si Administratiei</DEN_ORDONATOR>
    <COD_PROIECT>49</COD_PROIECT>
    <DENUMIRE>Proiectul privind constructia si reabilitarea de locuinte sociale pentru tineri destinate inchirierii</DENUMIRE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROGRAMULUI FINANTAT POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.05</ANEXA>
    <NRCRT>3</NRCRT>
    <COD_ORDONATOR>15</COD_ORDONATOR>
    <CODFISCAL>26369185</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Dezvoltarii, Lucrarilor Publice si Administratiei</DEN_ORDONATOR>
    <COD_PROIECT>49</COD_PROIECT>
    <COD_INDICATOR>5000</COD_INDICATOR>
    <DENUMIRE>TOTAL GENERAL</DENUMIRE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROGRAMULUI FINANTAT POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.05</ANEXA>
    <NRCRT>4</NRCRT>
    <COD_ORDONATOR>15</COD_ORDONATOR>
    <CODFISCAL>26369185</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Dezvoltarii, Lucrarilor Publice si Administratiei</DEN_ORDONATOR>
    <COD_PROIECT>49</COD_PROIECT>
    <COD_INDICATOR>5000</COD_INDICATOR>
    <DENUMIRE>I. Credite de angajament </DENUMIRE>
    <CHE_PANA_LA_31_12_2023>146069</CHE_PANA_LA_31_12_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>0</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ESTIMARI_ANII_ULTERIORI>0</ESTIMARI_ANII_ULTERIORI>
    <TOTAL>146069</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROGRAMULUI FINANTAT POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.05</ANEXA>
    <NRCRT>5</NRCRT>
    <COD_ORDONATOR>15</COD_ORDONATOR>
    <CODFISCAL>26369185</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Dezvoltarii, Lucrarilor Publice si Administratiei</DEN_ORDONATOR>
    <COD_PROIECT>49</COD_PROIECT>
    <COD_INDICATOR>5000</COD_INDICATOR>
    <DENUMIRE>II. Credite bugetare </DENUMIRE>
    <CHE_PANA_LA_31_12_2023>146069</CHE_PANA_LA_31_12_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>0</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ESTIMARI_ANII_ULTERIORI>0</ESTIMARI_ANII_ULTERIORI>
    <TOTAL>146069</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROGRAMULUI FINANTAT POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.05</ANEXA>
    <NRCRT>6</NRCRT>
    <COD_ORDONATOR>15</COD_ORDONATOR>
    <CODFISCAL>26369185</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Dezvoltarii, Lucrarilor Publice si Administratiei</DEN_ORDONATOR>
    <COD_PROIECT>49</COD_PROIECT>
    <DENUMIRE>Buget de stat</DENUMIRE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROGRAMULUI FINANTAT POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.05</ANEXA>
    <NRCRT>7</NRCRT>
    <COD_ORDONATOR>15</COD_ORDONATOR>
    <CODFISCAL>26369185</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Dezvoltarii, Lucrarilor Publice si Administratiei</DEN_ORDONATOR>
    <COD_PROIECT>49</COD_PROIECT>
    <COD_INDICATOR>5001</COD_INDICATOR>
    <DENUMIRE>CHELTUIELI - BUGET DE STAT</DENUMIRE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROGRAMULUI FINANTAT POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.05</ANEXA>
    <NRCRT>8</NRCRT>
    <COD_ORDONATOR>15</COD_ORDONATOR>
    <CODFISCAL>26369185</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Dezvoltarii, Lucrarilor Publice si Administratiei</DEN_ORDONATOR>
    <COD_PROIECT>49</COD_PROIECT>
    <COD_INDICATOR>5001</COD_INDICATOR>
    <DENUMIRE>I. Credite de angajament </DENUMIRE>
    <CHE_PANA_LA_31_12_2023>146069</CHE_PANA_LA_31_12_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>0</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ESTIMARI_ANII_ULTERIORI>0</ESTIMARI_ANII_ULTERIORI>
    <TOTAL>146069</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROGRAMULUI FINANTAT POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.05</ANEXA>
    <NRCRT>9</NRCRT>
    <COD_ORDONATOR>15</COD_ORDONATOR>
    <CODFISCAL>26369185</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Dezvoltarii, Lucrarilor Publice si Administratiei</DEN_ORDONATOR>
    <COD_PROIECT>49</COD_PROIECT>
    <COD_INDICATOR>5001</COD_INDICATOR>
    <DENUMIRE>II. Credite bugetare </DENUMIRE>
    <CHE_PANA_LA_31_12_2023>146069</CHE_PANA_LA_31_12_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>0</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ESTIMARI_ANII_ULTERIORI>0</ESTIMARI_ANII_ULTERIORI>
    <TOTAL>146069</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROGRAMULUI FINANTAT POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.05</ANEXA>
    <NRCRT>10</NRCRT>
    <COD_ORDONATOR>15</COD_ORDONATOR>
    <CODFISCAL>26369185</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Dezvoltarii, Lucrarilor Publice si Administratiei</DEN_ORDONATOR>
    <COD_PROIECT>49</COD_PROIECT>
    <COD_INDICATOR>7001</COD_INDICATOR>
    <DENUMIRE>LOCUINTE, SERVICII SI DEZVOLTARE PUBLICA</DENUMIRE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROGRAMULUI FINANTAT POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.05</ANEXA>
    <NRCRT>11</NRCRT>
    <COD_ORDONATOR>15</COD_ORDONATOR>
    <CODFISCAL>26369185</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Dezvoltarii, Lucrarilor Publice si Administratiei</DEN_ORDONATOR>
    <COD_PROIECT>49</COD_PROIECT>
    <COD_INDICATOR>7001</COD_INDICATOR>
    <DENUMIRE>I. Credite de angajament </DENUMIRE>
    <CHE_PANA_LA_31_12_2023>146069</CHE_PANA_LA_31_12_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>0</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ESTIMARI_ANII_ULTERIORI>0</ESTIMARI_ANII_ULTERIORI>
    <TOTAL>146069</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROGRAMULUI FINANTAT POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.05</ANEXA>
    <NRCRT>12</NRCRT>
    <COD_ORDONATOR>15</COD_ORDONATOR>
    <CODFISCAL>26369185</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Dezvoltarii, Lucrarilor Publice si Administratiei</DEN_ORDONATOR>
    <COD_PROIECT>49</COD_PROIECT>
    <COD_INDICATOR>7001</COD_INDICATOR>
    <DENUMIRE>II. Credite bugetare </DENUMIRE>
    <CHE_PANA_LA_31_12_2023>146069</CHE_PANA_LA_31_12_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>0</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ESTIMARI_ANII_ULTERIORI>0</ESTIMARI_ANII_ULTERIORI>
    <TOTAL>146069</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROGRAMULUI FINANTAT POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.05</ANEXA>
    <NRCRT>13</NRCRT>
    <COD_ORDONATOR>15</COD_ORDONATOR>
    <CODFISCAL>26369185</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Dezvoltarii, Lucrarilor Publice si Administratiei</DEN_ORDONATOR>
    <COD_PROIECT>49</COD_PROIECT>
    <COD_INDICATOR>700165</COD_INDICATOR>
    <DENUMIRE>TITLUL XIV CHELTUIELI AFERENTE PROGRAMELOR CU FINANTARE RAMBURSABILA</DENUMIRE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROGRAMULUI FINANTAT POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.05</ANEXA>
    <NRCRT>14</NRCRT>
    <COD_ORDONATOR>15</COD_ORDONATOR>
    <CODFISCAL>26369185</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Dezvoltarii, Lucrarilor Publice si Administratiei</DEN_ORDONATOR>
    <COD_PROIECT>49</COD_PROIECT>
    <COD_INDICATOR>700165</COD_INDICATOR>
    <DENUMIRE>I. Credite de angajament </DENUMIRE>
    <CHE_PANA_LA_31_12_2023>146069</CHE_PANA_LA_31_12_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>0</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ESTIMARI_ANII_ULTERIORI>0</ESTIMARI_ANII_ULTERIORI>
    <TOTAL>146069</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROGRAMULUI FINANTAT POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.05</ANEXA>
    <NRCRT>15</NRCRT>
    <COD_ORDONATOR>15</COD_ORDONATOR>
    <CODFISCAL>26369185</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Dezvoltarii, Lucrarilor Publice si Administratiei</DEN_ORDONATOR>
    <COD_PROIECT>49</COD_PROIECT>
    <COD_INDICATOR>700165</COD_INDICATOR>
    <DENUMIRE>II. Credite bugetare </DENUMIRE>
    <CHE_PANA_LA_31_12_2023>146069</CHE_PANA_LA_31_12_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>0</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ESTIMARI_ANII_ULTERIORI>0</ESTIMARI_ANII_ULTERIORI>
    <TOTAL>146069</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROGRAMULUI FINANTAT POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.05</ANEXA>
    <NRCRT>16</NRCRT>
    <COD_ORDONATOR>15</COD_ORDONATOR>
    <CODFISCAL>26369185</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Dezvoltarii, Lucrarilor Publice si Administratiei</DEN_ORDONATOR>
    <COD_PROIECT>56</COD_PROIECT>
    <DENUMIRE>Proiectul pentru realizarea sistemului de alimentare cu apa si canalizare in localitatile sub 50.000 de locuitori</DENUMIRE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROGRAMULUI FINANTAT POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.05</ANEXA>
    <NRCRT>17</NRCRT>
    <COD_ORDONATOR>15</COD_ORDONATOR>
    <CODFISCAL>26369185</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Dezvoltarii, Lucrarilor Publice si Administratiei</DEN_ORDONATOR>
    <COD_PROIECT>56</COD_PROIECT>
    <COD_INDICATOR>5000</COD_INDICATOR>
    <DENUMIRE>TOTAL GENERAL</DENUMIRE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROGRAMULUI FINANTAT POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.05</ANEXA>
    <NRCRT>18</NRCRT>
    <COD_ORDONATOR>15</COD_ORDONATOR>
    <CODFISCAL>26369185</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Dezvoltarii, Lucrarilor Publice si Administratiei</DEN_ORDONATOR>
    <COD_PROIECT>56</COD_PROIECT>
    <COD_INDICATOR>5000</COD_INDICATOR>
    <DENUMIRE>I. Credite de angajament </DENUMIRE>
    <CHE_PANA_LA_31_12_2023>613123</CHE_PANA_LA_31_12_2023>
    <EXECUTIE_PRELIMINATA_2024>2895</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>30000</PROGRAM_2025>
    <ESTIMARI_2026>5000</ESTIMARI_2026>
    <ESTIMARI_2027>5000</ESTIMARI_2027>
    <ESTIMARI_2028>1000</ESTIMARI_2028>
    <ESTIMARI_ANII_ULTERIORI>0</ESTIMARI_ANII_ULTERIORI>
    <TOTAL>657018</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROGRAMULUI FINANTAT POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.05</ANEXA>
    <NRCRT>19</NRCRT>
    <COD_ORDONATOR>15</COD_ORDONATOR>
    <CODFISCAL>26369185</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Dezvoltarii, Lucrarilor Publice si Administratiei</DEN_ORDONATOR>
    <COD_PROIECT>56</COD_PROIECT>
    <COD_INDICATOR>5000</COD_INDICATOR>
    <DENUMIRE>II. Credite bugetare </DENUMIRE>
    <CHE_PANA_LA_31_12_2023>613123</CHE_PANA_LA_31_12_2023>
    <EXECUTIE_PRELIMINATA_2024>2500</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>2000</PROGRAM_2025>
    <ESTIMARI_2026>5000</ESTIMARI_2026>
    <ESTIMARI_2027>5000</ESTIMARI_2027>
    <ESTIMARI_2028>1000</ESTIMARI_2028>
    <ESTIMARI_ANII_ULTERIORI>28395</ESTIMARI_ANII_ULTERIORI>
    <TOTAL>657018</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROGRAMULUI FINANTAT POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.05</ANEXA>
    <NRCRT>20</NRCRT>
    <COD_ORDONATOR>15</COD_ORDONATOR>
    <CODFISCAL>26369185</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Dezvoltarii, Lucrarilor Publice si Administratiei</DEN_ORDONATOR>
    <COD_PROIECT>56</COD_PROIECT>
    <DENUMIRE>Buget de stat</DENUMIRE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROGRAMULUI FINANTAT POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.05</ANEXA>
    <NRCRT>21</NRCRT>
    <COD_ORDONATOR>15</COD_ORDONATOR>
    <CODFISCAL>26369185</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Dezvoltarii, Lucrarilor Publice si Administratiei</DEN_ORDONATOR>
    <COD_PROIECT>56</COD_PROIECT>
    <COD_INDICATOR>5001</COD_INDICATOR>
    <DENUMIRE>CHELTUIELI - BUGET DE STAT</DENUMIRE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROGRAMULUI FINANTAT POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.05</ANEXA>
    <NRCRT>22</NRCRT>
    <COD_ORDONATOR>15</COD_ORDONATOR>
    <CODFISCAL>26369185</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Dezvoltarii, Lucrarilor Publice si Administratiei</DEN_ORDONATOR>
    <COD_PROIECT>56</COD_PROIECT>
    <COD_INDICATOR>5001</COD_INDICATOR>
    <DENUMIRE>I. Credite de angajament </DENUMIRE>
    <CHE_PANA_LA_31_12_2023>613123</CHE_PANA_LA_31_12_2023>
    <EXECUTIE_PRELIMINATA_2024>2895</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>30000</PROGRAM_2025>
    <ESTIMARI_2026>5000</ESTIMARI_2026>
    <ESTIMARI_2027>5000</ESTIMARI_2027>
    <ESTIMARI_2028>1000</ESTIMARI_2028>
    <ESTIMARI_ANII_ULTERIORI>0</ESTIMARI_ANII_ULTERIORI>
    <TOTAL>657018</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROGRAMULUI FINANTAT POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.05</ANEXA>
    <NRCRT>23</NRCRT>
    <COD_ORDONATOR>15</COD_ORDONATOR>
    <CODFISCAL>26369185</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Dezvoltarii, Lucrarilor Publice si Administratiei</DEN_ORDONATOR>
    <COD_PROIECT>56</COD_PROIECT>
    <COD_INDICATOR>5001</COD_INDICATOR>
    <DENUMIRE>II. Credite bugetare </DENUMIRE>
    <CHE_PANA_LA_31_12_2023>613123</CHE_PANA_LA_31_12_2023>
    <EXECUTIE_PRELIMINATA_2024>2500</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>2000</PROGRAM_2025>
    <ESTIMARI_2026>5000</ESTIMARI_2026>
    <ESTIMARI_2027>5000</ESTIMARI_2027>
    <ESTIMARI_2028>1000</ESTIMARI_2028>
    <ESTIMARI_ANII_ULTERIORI>28395</ESTIMARI_ANII_ULTERIORI>
    <TOTAL>657018</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROGRAMULUI FINANTAT POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.05</ANEXA>
    <NRCRT>24</NRCRT>
    <COD_ORDONATOR>15</COD_ORDONATOR>
    <CODFISCAL>26369185</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Dezvoltarii, Lucrarilor Publice si Administratiei</DEN_ORDONATOR>
    <COD_PROIECT>56</COD_PROIECT>
    <COD_INDICATOR>7001</COD_INDICATOR>
    <DENUMIRE>LOCUINTE, SERVICII SI DEZVOLTARE PUBLICA</DENUMIRE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROGRAMULUI FINANTAT POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.05</ANEXA>
    <NRCRT>25</NRCRT>
    <COD_ORDONATOR>15</COD_ORDONATOR>
    <CODFISCAL>26369185</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Dezvoltarii, Lucrarilor Publice si Administratiei</DEN_ORDONATOR>
    <COD_PROIECT>56</COD_PROIECT>
    <COD_INDICATOR>7001</COD_INDICATOR>
    <DENUMIRE>I. Credite de angajament </DENUMIRE>
    <CHE_PANA_LA_31_12_2023>613123</CHE_PANA_LA_31_12_2023>
    <EXECUTIE_PRELIMINATA_2024>2895</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>30000</PROGRAM_2025>
    <ESTIMARI_2026>5000</ESTIMARI_2026>
    <ESTIMARI_2027>5000</ESTIMARI_2027>
    <ESTIMARI_2028>1000</ESTIMARI_2028>
    <ESTIMARI_ANII_ULTERIORI>0</ESTIMARI_ANII_ULTERIORI>
    <TOTAL>657018</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROGRAMULUI FINANTAT POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.05</ANEXA>
    <NRCRT>26</NRCRT>
    <COD_ORDONATOR>15</COD_ORDONATOR>
    <CODFISCAL>26369185</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Dezvoltarii, Lucrarilor Publice si Administratiei</DEN_ORDONATOR>
    <COD_PROIECT>56</COD_PROIECT>
    <COD_INDICATOR>7001</COD_INDICATOR>
    <DENUMIRE>II. Credite bugetare </DENUMIRE>
    <CHE_PANA_LA_31_12_2023>613123</CHE_PANA_LA_31_12_2023>
    <EXECUTIE_PRELIMINATA_2024>2500</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>2000</PROGRAM_2025>
    <ESTIMARI_2026>5000</ESTIMARI_2026>
    <ESTIMARI_2027>5000</ESTIMARI_2027>
    <ESTIMARI_2028>1000</ESTIMARI_2028>
    <ESTIMARI_ANII_ULTERIORI>28395</ESTIMARI_ANII_ULTERIORI>
    <TOTAL>657018</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROGRAMULUI FINANTAT POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.05</ANEXA>
    <NRCRT>27</NRCRT>
    <COD_ORDONATOR>15</COD_ORDONATOR>
    <CODFISCAL>26369185</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Dezvoltarii, Lucrarilor Publice si Administratiei</DEN_ORDONATOR>
    <COD_PROIECT>56</COD_PROIECT>
    <COD_INDICATOR>700165</COD_INDICATOR>
    <DENUMIRE>TITLUL XIV CHELTUIELI AFERENTE PROGRAMELOR CU FINANTARE RAMBURSABILA</DENUMIRE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROGRAMULUI FINANTAT POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.05</ANEXA>
    <NRCRT>28</NRCRT>
    <COD_ORDONATOR>15</COD_ORDONATOR>
    <CODFISCAL>26369185</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Dezvoltarii, Lucrarilor Publice si Administratiei</DEN_ORDONATOR>
    <COD_PROIECT>56</COD_PROIECT>
    <COD_INDICATOR>700165</COD_INDICATOR>
    <DENUMIRE>I. Credite de angajament </DENUMIRE>
    <CHE_PANA_LA_31_12_2023>613123</CHE_PANA_LA_31_12_2023>
    <EXECUTIE_PRELIMINATA_2024>2895</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>30000</PROGRAM_2025>
    <ESTIMARI_2026>5000</ESTIMARI_2026>
    <ESTIMARI_2027>5000</ESTIMARI_2027>
    <ESTIMARI_2028>1000</ESTIMARI_2028>
    <ESTIMARI_ANII_ULTERIORI>0</ESTIMARI_ANII_ULTERIORI>
    <TOTAL>657018</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>FISA PROGRAMULUI FINANTAT POTRIVIT ORDONANTEI DE URGENTA A GUVERNULUI NR. 64/2007</TITLU_RAPORT>
    <ANEXA>Anexa nr.05</ANEXA>
    <NRCRT>29</NRCRT>
    <COD_ORDONATOR>15</COD_ORDONATOR>
    <CODFISCAL>26369185</CODFISCAL>
    <DEN_ORDONATOR>Ministerul Dezvoltarii, Lucrarilor Publice si Administratiei</DEN_ORDONATOR>
    <COD_PROIECT>56</COD_PROIECT>
    <COD_INDICATOR>700165</COD_INDICATOR>
    <DENUMIRE>II. Credite bugetare </DENUMIRE>
    <CHE_PANA_LA_31_12_2023>613123</CHE_PANA_LA_31_12_2023>
    <EXECUTIE_PRELIMINATA_2024>2500</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>2000</PROGRAM_2025>
    <ESTIMARI_2026>5000</ESTIMARI_2026>
    <ESTIMARI_2027>5000</ESTIMARI_2027>
    <ESTIMARI_2028>1000</ESTIMARI_2028>
    <ESTIMARI_ANII_ULTERIORI>28395</ESTIMARI_ANII_ULTERIORI>