<?xml version="1.0" ?>
<!DOCTYPE main [
  <!ELEMENT main (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (TITLU_RAPORT,ANEXA?,COD_ORDONATOR?,DEN_ORDONATOR,CODFISCAL,COD_PROIECT,DEN_PROIECT,COD_INDICATOR,DEN_INDICATOR,CATEGORIE_RAND?,REALIZARI_PANA_IN_2022,REALIZARI_2023,EXECUTIE_PRELIMINATA_2024,PROGRAM_2025,ESTIMARI_2026,ESTIMARI_2027,ESTIMARI_2028,ANII_URMATORI,TOTAL)+>
  <!ELEMENT TITLU_RAPORT (#PCDATA)>
  <!ELEMENT ANEXA (#PCDATA)>
  <!ELEMENT COD_ORDONATOR (#PCDATA)>
  <!ELEMENT DEN_ORDONATOR (#PCDATA)>
  <!ELEMENT CODFISCAL (#PCDATA)>
  <!ELEMENT COD_PROIECT (#PCDATA)>
  <!ELEMENT DEN_PROIECT (#PCDATA)>
  <!ELEMENT COD_INDICATOR (#PCDATA)>
  <!ELEMENT DEN_INDICATOR (#PCDATA)>
  <!ELEMENT CATEGORIE_RAND (#PCDATA)>
  <!ELEMENT REALIZARI_PANA_IN_2022 (#PCDATA)>
  <!ELEMENT REALIZARI_2023 (#PCDATA)>
  <!ELEMENT EXECUTIE_PRELIMINATA_2024 (#PCDATA)>
  <!ELEMENT PROGRAM_2025 (#PCDATA)>
  <!ELEMENT ESTIMARI_2026 (#PCDATA)>
  <!ELEMENT ESTIMARI_2027 (#PCDATA)>
  <!ELEMENT ESTIMARI_2028 (#PCDATA)>
  <!ELEMENT ANII_URMATORI (#PCDATA)>
  <!ELEMENT TOTAL (#PCDATA)>
]>
<main>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA PROIECTELOR FINANTATE/PROPUSE LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT, PRECUM SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 10/04</ANEXA>
    <COD_ORDONATOR>01</COD_ORDONATOR>
    <DEN_ORDONATOR>Casa Nationala de Asigurari de Sanatate</DEN_ORDONATOR>
    <CODFISCAL>11697800</CODFISCAL>
    <COD_PROIECT>0</COD_PROIECT>
    <DEN_PROIECT>TOTAL PROIECTE</DEN_PROIECT>
    <COD_INDICATOR>5000</COD_INDICATOR>
    <DEN_INDICATOR>TOTAL GENERAL</DEN_INDICATOR>
    <CATEGORIE_RAND>I.  Credite de angajament</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>103813</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>5019</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>150</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>27290</PROGRAM_2025>
    <ESTIMARI_2026>1743</ESTIMARI_2026>
    <ESTIMARI_2027>1468</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>139483</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA PROIECTELOR FINANTATE/PROPUSE LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT, PRECUM SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 10/04</ANEXA>
    <COD_ORDONATOR>01</COD_ORDONATOR>
    <DEN_ORDONATOR>Casa Nationala de Asigurari de Sanatate</DEN_ORDONATOR>
    <CODFISCAL>11697800</CODFISCAL>
    <COD_PROIECT>0</COD_PROIECT>
    <DEN_PROIECT>TOTAL PROIECTE</DEN_PROIECT>
    <COD_INDICATOR>5000</COD_INDICATOR>
    <DEN_INDICATOR>TOTAL GENERAL</DEN_INDICATOR>
    <CATEGORIE_RAND>II. Credite bugetare</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>5410</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>103422</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>150</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>14645</PROGRAM_2025>
    <ESTIMARI_2026>8773</ESTIMARI_2026>
    <ESTIMARI_2027>7083</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>139483</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA PROIECTELOR FINANTATE/PROPUSE LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT, PRECUM SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 10/04</ANEXA>
    <COD_ORDONATOR>01</COD_ORDONATOR>
    <DEN_ORDONATOR>Casa Nationala de Asigurari de Sanatate</DEN_ORDONATOR>
    <CODFISCAL>11697800</CODFISCAL>
    <COD_PROIECT>0</COD_PROIECT>
    <DEN_PROIECT>TOTAL PROIECTE</DEN_PROIECT>
    <COD_INDICATOR>66055672</COD_INDICATOR>
    <DEN_INDICATOR>Alte programe comunitare finantate in perioada 2021-2027</DEN_INDICATOR>
    <CATEGORIE_RAND>I.  Credite de angajament</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>90</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>19360</PROGRAM_2025>
    <ESTIMARI_2026>1187</ESTIMARI_2026>
    <ESTIMARI_2027>962</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>21599</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA PROIECTELOR FINANTATE/PROPUSE LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT, PRECUM SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 10/04</ANEXA>
    <COD_ORDONATOR>01</COD_ORDONATOR>
    <DEN_ORDONATOR>Casa Nationala de Asigurari de Sanatate</DEN_ORDONATOR>
    <CODFISCAL>11697800</CODFISCAL>
    <COD_PROIECT>0</COD_PROIECT>
    <DEN_PROIECT>TOTAL PROIECTE</DEN_PROIECT>
    <COD_INDICATOR>66055672</COD_INDICATOR>
    <DEN_INDICATOR>Alte programe comunitare finantate in perioada 2021-2027</DEN_INDICATOR>
    <CATEGORIE_RAND>II. Credite bugetare</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>90</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>10285</PROGRAM_2025>
    <ESTIMARI_2026>6162</ESTIMARI_2026>
    <ESTIMARI_2027>5062</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>21599</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA PROIECTELOR FINANTATE/PROPUSE LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT, PRECUM SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 10/04</ANEXA>
    <COD_ORDONATOR>01</COD_ORDONATOR>
    <DEN_ORDONATOR>Casa Nationala de Asigurari de Sanatate</DEN_ORDONATOR>
    <CODFISCAL>11697800</CODFISCAL>
    <COD_PROIECT>0</COD_PROIECT>
    <DEN_PROIECT>TOTAL PROIECTE</DEN_PROIECT>
    <COD_INDICATOR>6605567201</COD_INDICATOR>
    <DEN_INDICATOR>Finantare nationala</DEN_INDICATOR>
    <CATEGORIE_RAND>I.  Credite de angajament</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>30</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>5458</PROGRAM_2025>
    <ESTIMARI_2026>349</ESTIMARI_2026>
    <ESTIMARI_2027>294</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>6131</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA PROIECTELOR FINANTATE/PROPUSE LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT, PRECUM SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 10/04</ANEXA>
    <COD_ORDONATOR>01</COD_ORDONATOR>
    <DEN_ORDONATOR>Casa Nationala de Asigurari de Sanatate</DEN_ORDONATOR>
    <CODFISCAL>11697800</CODFISCAL>
    <COD_PROIECT>0</COD_PROIECT>
    <DEN_PROIECT>TOTAL PROIECTE</DEN_PROIECT>
    <COD_INDICATOR>6605567201</COD_INDICATOR>
    <DEN_INDICATOR>Finantare nationala</DEN_INDICATOR>
    <CATEGORIE_RAND>II. Credite bugetare</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>30</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>2929</PROGRAM_2025>
    <ESTIMARI_2026>1755</ESTIMARI_2026>
    <ESTIMARI_2027>1417</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>6131</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA PROIECTELOR FINANTATE/PROPUSE LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT, PRECUM SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 10/04</ANEXA>
    <COD_ORDONATOR>01</COD_ORDONATOR>
    <DEN_ORDONATOR>Casa Nationala de Asigurari de Sanatate</DEN_ORDONATOR>
    <CODFISCAL>11697800</CODFISCAL>
    <COD_PROIECT>0</COD_PROIECT>
    <DEN_PROIECT>TOTAL PROIECTE</DEN_PROIECT>
    <COD_INDICATOR>6605567202</COD_INDICATOR>
    <DEN_INDICATOR>Finantare externa nerambursabila</DEN_INDICATOR>
    <CATEGORIE_RAND>I.  Credite de angajament</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>60</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>13902</PROGRAM_2025>
    <ESTIMARI_2026>838</ESTIMARI_2026>
    <ESTIMARI_2027>668</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>15468</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA PROIECTELOR FINANTATE/PROPUSE LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT, PRECUM SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 10/04</ANEXA>
    <COD_ORDONATOR>01</COD_ORDONATOR>
    <DEN_ORDONATOR>Casa Nationala de Asigurari de Sanatate</DEN_ORDONATOR>
    <CODFISCAL>11697800</CODFISCAL>
    <COD_PROIECT>0</COD_PROIECT>
    <DEN_PROIECT>TOTAL PROIECTE</DEN_PROIECT>
    <COD_INDICATOR>6605567202</COD_INDICATOR>
    <DEN_INDICATOR>Finantare externa nerambursabila</DEN_INDICATOR>
    <CATEGORIE_RAND>II. Credite bugetare</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>60</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>7356</PROGRAM_2025>
    <ESTIMARI_2026>4407</ESTIMARI_2026>
    <ESTIMARI_2027>3645</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>15468</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA PROIECTELOR FINANTATE/PROPUSE LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT, PRECUM SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 10/04</ANEXA>
    <COD_ORDONATOR>01</COD_ORDONATOR>
    <DEN_ORDONATOR>Casa Nationala de Asigurari de Sanatate</DEN_ORDONATOR>
    <CODFISCAL>11697800</CODFISCAL>
    <COD_PROIECT>0</COD_PROIECT>
    <DEN_PROIECT>TOTAL PROIECTE</DEN_PROIECT>
    <COD_INDICATOR>66055802</COD_INDICATOR>
    <DEN_INDICATOR>Programe din Fondul Social European &#40;FSE&#41;</DEN_INDICATOR>
    <CATEGORIE_RAND>I.  Credite de angajament</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>102924</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>5019</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>0</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>107943</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA PROIECTELOR FINANTATE/PROPUSE LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT, PRECUM SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 10/04</ANEXA>
    <COD_ORDONATOR>01</COD_ORDONATOR>
    <DEN_ORDONATOR>Casa Nationala de Asigurari de Sanatate</DEN_ORDONATOR>
    <CODFISCAL>11697800</CODFISCAL>
    <COD_PROIECT>0</COD_PROIECT>
    <DEN_PROIECT>TOTAL PROIECTE</DEN_PROIECT>
    <COD_INDICATOR>66055802</COD_INDICATOR>
    <DEN_INDICATOR>Programe din Fondul Social European &#40;FSE&#41;</DEN_INDICATOR>
    <CATEGORIE_RAND>II. Credite bugetare</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>4521</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>103422</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>0</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>107943</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA PROIECTELOR FINANTATE/PROPUSE LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT, PRECUM SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 10/04</ANEXA>
    <COD_ORDONATOR>01</COD_ORDONATOR>
    <DEN_ORDONATOR>Casa Nationala de Asigurari de Sanatate</DEN_ORDONATOR>
    <CODFISCAL>11697800</CODFISCAL>
    <COD_PROIECT>0</COD_PROIECT>
    <DEN_PROIECT>TOTAL PROIECTE</DEN_PROIECT>
    <COD_INDICATOR>6605580201</COD_INDICATOR>
    <DEN_INDICATOR> Finantarea nationala</DEN_INDICATOR>
    <CATEGORIE_RAND>I.  Credite de angajament</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>16298</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>359</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>0</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>16657</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA PROIECTELOR FINANTATE/PROPUSE LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT, PRECUM SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 10/04</ANEXA>
    <COD_ORDONATOR>01</COD_ORDONATOR>
    <DEN_ORDONATOR>Casa Nationala de Asigurari de Sanatate</DEN_ORDONATOR>
    <CODFISCAL>11697800</CODFISCAL>
    <COD_PROIECT>0</COD_PROIECT>
    <DEN_PROIECT>TOTAL PROIECTE</DEN_PROIECT>
    <COD_INDICATOR>6605580201</COD_INDICATOR>
    <DEN_INDICATOR> Finantarea nationala</DEN_INDICATOR>
    <CATEGORIE_RAND>II. Credite bugetare</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>538</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>16119</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>0</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>16657</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA PROIECTELOR FINANTATE/PROPUSE LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT, PRECUM SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 10/04</ANEXA>
    <COD_ORDONATOR>01</COD_ORDONATOR>
    <DEN_ORDONATOR>Casa Nationala de Asigurari de Sanatate</DEN_ORDONATOR>
    <CODFISCAL>11697800</CODFISCAL>
    <COD_PROIECT>0</COD_PROIECT>
    <DEN_PROIECT>TOTAL PROIECTE</DEN_PROIECT>
    <COD_INDICATOR>6605580202</COD_INDICATOR>
    <DEN_INDICATOR> Finantarea externa nerambursabila</DEN_INDICATOR>
    <CATEGORIE_RAND>I.  Credite de angajament</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>86626</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>4660</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>0</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>91286</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA PROIECTELOR FINANTATE/PROPUSE LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT, PRECUM SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 10/04</ANEXA>
    <COD_ORDONATOR>01</COD_ORDONATOR>
    <DEN_ORDONATOR>Casa Nationala de Asigurari de Sanatate</DEN_ORDONATOR>
    <CODFISCAL>11697800</CODFISCAL>
    <COD_PROIECT>0</COD_PROIECT>
    <DEN_PROIECT>TOTAL PROIECTE</DEN_PROIECT>
    <COD_INDICATOR>6605580202</COD_INDICATOR>
    <DEN_INDICATOR> Finantarea externa nerambursabila</DEN_INDICATOR>
    <CATEGORIE_RAND>II. Credite bugetare</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>3983</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>87303</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>0</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>91286</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA PROIECTELOR FINANTATE/PROPUSE LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT, PRECUM SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 10/04</ANEXA>
    <COD_ORDONATOR>01</COD_ORDONATOR>
    <DEN_ORDONATOR>Casa Nationala de Asigurari de Sanatate</DEN_ORDONATOR>
    <CODFISCAL>11697800</CODFISCAL>
    <COD_PROIECT>0</COD_PROIECT>
    <DEN_PROIECT>TOTAL PROIECTE</DEN_PROIECT>
    <COD_INDICATOR>66055815</COD_INDICATOR>
    <DEN_INDICATOR>Alte programe comunitare finantate in perioada 2014-2020</DEN_INDICATOR>
    <CATEGORIE_RAND>I.  Credite de angajament</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>599</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>0</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>599</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA PROIECTELOR FINANTATE/PROPUSE LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT, PRECUM SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 10/04</ANEXA>
    <COD_ORDONATOR>01</COD_ORDONATOR>
    <DEN_ORDONATOR>Casa Nationala de Asigurari de Sanatate</DEN_ORDONATOR>
    <CODFISCAL>11697800</CODFISCAL>
    <COD_PROIECT>0</COD_PROIECT>
    <DEN_PROIECT>TOTAL PROIECTE</DEN_PROIECT>
    <COD_INDICATOR>66055815</COD_INDICATOR>
    <DEN_INDICATOR>Alte programe comunitare finantate in perioada 2014-2020</DEN_INDICATOR>
    <CATEGORIE_RAND>II. Credite bugetare</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>599</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>0</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>599</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA PROIECTELOR FINANTATE/PROPUSE LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT, PRECUM SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 10/04</ANEXA>
    <COD_ORDONATOR>01</COD_ORDONATOR>
    <DEN_ORDONATOR>Casa Nationala de Asigurari de Sanatate</DEN_ORDONATOR>
    <CODFISCAL>11697800</CODFISCAL>
    <COD_PROIECT>0</COD_PROIECT>
    <DEN_PROIECT>TOTAL PROIECTE</DEN_PROIECT>
    <COD_INDICATOR>6605581501</COD_INDICATOR>
    <DEN_INDICATOR>Finantarea nationala</DEN_INDICATOR>
    <CATEGORIE_RAND>I.  Credite de angajament</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>194</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>0</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>194</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA PROIECTELOR FINANTATE/PROPUSE LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT, PRECUM SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 10/04</ANEXA>
    <COD_ORDONATOR>01</COD_ORDONATOR>
    <DEN_ORDONATOR>Casa Nationala de Asigurari de Sanatate</DEN_ORDONATOR>
    <CODFISCAL>11697800</CODFISCAL>
    <COD_PROIECT>0</COD_PROIECT>
    <DEN_PROIECT>TOTAL PROIECTE</DEN_PROIECT>
    <COD_INDICATOR>6605581501</COD_INDICATOR>
    <DEN_INDICATOR>Finantarea nationala</DEN_INDICATOR>
    <CATEGORIE_RAND>II. Credite bugetare</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>194</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>0</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>194</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA PROIECTELOR FINANTATE/PROPUSE LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT, PRECUM SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 10/04</ANEXA>
    <COD_ORDONATOR>01</COD_ORDONATOR>
    <DEN_ORDONATOR>Casa Nationala de Asigurari de Sanatate</DEN_ORDONATOR>
    <CODFISCAL>11697800</CODFISCAL>
    <COD_PROIECT>0</COD_PROIECT>
    <DEN_PROIECT>TOTAL PROIECTE</DEN_PROIECT>
    <COD_INDICATOR>6605581502</COD_INDICATOR>
    <DEN_INDICATOR>Finantare externa nerambursabila</DEN_INDICATOR>
    <CATEGORIE_RAND>I.  Credite de angajament</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>290</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>0</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>290</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA PROIECTELOR FINANTATE/PROPUSE LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT, PRECUM SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 10/04</ANEXA>
    <COD_ORDONATOR>01</COD_ORDONATOR>
    <DEN_ORDONATOR>Casa Nationala de Asigurari de Sanatate</DEN_ORDONATOR>
    <CODFISCAL>11697800</CODFISCAL>
    <COD_PROIECT>0</COD_PROIECT>
    <DEN_PROIECT>TOTAL PROIECTE</DEN_PROIECT>
    <COD_INDICATOR>6605581502</COD_INDICATOR>
    <DEN_INDICATOR>Finantare externa nerambursabila</DEN_INDICATOR>
    <CATEGORIE_RAND>II. Credite bugetare</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>290</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>0</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>290</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA PROIECTELOR FINANTATE/PROPUSE LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT, PRECUM SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 10/04</ANEXA>
    <COD_ORDONATOR>01</COD_ORDONATOR>
    <DEN_ORDONATOR>Casa Nationala de Asigurari de Sanatate</DEN_ORDONATOR>
    <CODFISCAL>11697800</CODFISCAL>
    <COD_PROIECT>0</COD_PROIECT>
    <DEN_PROIECT>TOTAL PROIECTE</DEN_PROIECT>
    <COD_INDICATOR>6605581503</COD_INDICATOR>
    <DEN_INDICATOR>Cheltuieli neeligibile</DEN_INDICATOR>
    <CATEGORIE_RAND>I.  Credite de angajament</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>115</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>0</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>115</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA PROIECTELOR FINANTATE/PROPUSE LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT, PRECUM SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 10/04</ANEXA>
    <COD_ORDONATOR>01</COD_ORDONATOR>
    <DEN_ORDONATOR>Casa Nationala de Asigurari de Sanatate</DEN_ORDONATOR>
    <CODFISCAL>11697800</CODFISCAL>
    <COD_PROIECT>0</COD_PROIECT>
    <DEN_PROIECT>TOTAL PROIECTE</DEN_PROIECT>
    <COD_INDICATOR>6605581503</COD_INDICATOR>
    <DEN_INDICATOR>Cheltuieli neeligibile</DEN_INDICATOR>
    <CATEGORIE_RAND>II. Credite bugetare</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>115</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>0</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>0</PROGRAM_2025>
    <ESTIMARI_2026>0</ESTIMARI_2026>
    <ESTIMARI_2027>0</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>115</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA PROIECTELOR FINANTATE/PROPUSE LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT, PRECUM SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 10/04</ANEXA>
    <COD_ORDONATOR>01</COD_ORDONATOR>
    <DEN_ORDONATOR>Casa Nationala de Asigurari de Sanatate</DEN_ORDONATOR>
    <CODFISCAL>11697800</CODFISCAL>
    <COD_PROIECT>0</COD_PROIECT>
    <DEN_PROIECT>TOTAL PROIECTE</DEN_PROIECT>
    <COD_INDICATOR>66085672</COD_INDICATOR>
    <DEN_INDICATOR>Alte programe comunitare finantate in perioada 2021-2027</DEN_INDICATOR>
    <CATEGORIE_RAND>I.  Credite de angajament</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>60</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>7930</PROGRAM_2025>
    <ESTIMARI_2026>556</ESTIMARI_2026>
    <ESTIMARI_2027>506</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>9052</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA PROIECTELOR FINANTATE/PROPUSE LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT, PRECUM SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 10/04</ANEXA>
    <COD_ORDONATOR>01</COD_ORDONATOR>
    <DEN_ORDONATOR>Casa Nationala de Asigurari de Sanatate</DEN_ORDONATOR>
    <CODFISCAL>11697800</CODFISCAL>
    <COD_PROIECT>0</COD_PROIECT>
    <DEN_PROIECT>TOTAL PROIECTE</DEN_PROIECT>
    <COD_INDICATOR>66085672</COD_INDICATOR>
    <DEN_INDICATOR>Alte programe comunitare finantate in perioada 2021-2027</DEN_INDICATOR>
    <CATEGORIE_RAND>II. Credite bugetare</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>60</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>4360</PROGRAM_2025>
    <ESTIMARI_2026>2611</ESTIMARI_2026>
    <ESTIMARI_2027>2021</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>9052</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA PROIECTELOR FINANTATE/PROPUSE LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT, PRECUM SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 10/04</ANEXA>
    <COD_ORDONATOR>01</COD_ORDONATOR>
    <DEN_ORDONATOR>Casa Nationala de Asigurari de Sanatate</DEN_ORDONATOR>
    <CODFISCAL>11697800</CODFISCAL>
    <COD_PROIECT>0</COD_PROIECT>
    <DEN_PROIECT>TOTAL PROIECTE</DEN_PROIECT>
    <COD_INDICATOR>6608567202</COD_INDICATOR>
    <DEN_INDICATOR>Finantare externa nerambursabila</DEN_INDICATOR>
    <CATEGORIE_RAND>I.  Credite de angajament</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>60</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>7930</PROGRAM_2025>
    <ESTIMARI_2026>556</ESTIMARI_2026>
    <ESTIMARI_2027>506</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>9052</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA PROIECTELOR FINANTATE/PROPUSE LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT, PRECUM SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 10/04</ANEXA>
    <COD_ORDONATOR>01</COD_ORDONATOR>
    <DEN_ORDONATOR>Casa Nationala de Asigurari de Sanatate</DEN_ORDONATOR>
    <CODFISCAL>11697800</CODFISCAL>
    <COD_PROIECT>0</COD_PROIECT>
    <DEN_PROIECT>TOTAL PROIECTE</DEN_PROIECT>
    <COD_INDICATOR>6608567202</COD_INDICATOR>
    <DEN_INDICATOR>Finantare externa nerambursabila</DEN_INDICATOR>
    <CATEGORIE_RAND>II. Credite bugetare</CATEGORIE_RAND>
    <REALIZARI_PANA_IN_2022>0</REALIZARI_PANA_IN_2022>
    <REALIZARI_2023>0</REALIZARI_2023>
    <EXECUTIE_PRELIMINATA_2024>60</EXECUTIE_PRELIMINATA_2024>
    <PROGRAM_2025>4360</PROGRAM_2025>
    <ESTIMARI_2026>2611</ESTIMARI_2026>
    <ESTIMARI_2027>2021</ESTIMARI_2027>
    <ESTIMARI_2028>0</ESTIMARI_2028>
    <ANII_URMATORI>0</ANII_URMATORI>
    <TOTAL>9052</TOTAL>
  </DATA_RECORD>
  <DATA_RECORD>
    <TITLU_RAPORT>SINTEZA PROIECTELOR FINANTATE/PROPUSE LA FINANTARE IN CADRUL PROGRAMELOR AFERENTE POLITICII DE COEZIUNE A U.E, POLITICILOR COMUNE AGRICOLA SI DE PESCUIT, PRECUM SI A ALTOR FACILITATI SI INSTRUMENTE POSTADERARE</TITLU_RAPORT>
    <ANEXA>Anexa nr. 10/04</ANEXA>
    <COD_ORDONATOR>01</COD_ORDONATOR>
    <DEN_ORDONATOR>Casa Nationala de Asigurari de Sanatate</DEN_ORDONATOR>
    <CODFISCAL>11697800</CODFISCAL>
    <COD_PROIECT>0</COD_PROIECT>
    <DEN_PROIECT>TOTAL PROIECTE</DEN_PROIECT>
    <COD_INDICATOR>66085815</COD_INDICATOR>
    <DEN_INDICATOR>Alte programe comunitare finantate in perioada 2014-2020</DEN_INDICATOR>
    <CATEGORIE_RAND>I.  Credite de angajament</CATEGORIE_RAND>